"""
Build the GitHub Pages site directory from a finished CI run's reports.

Layout:
  gh-pages-site/
    index.html                  — landing page with stats + links to everything
    report.html                 — full master consolidated bug report
    agents/
      qa01-functional.html      — per-agent reports (links from index)
      qa02-edge.html
      ...
    history/
      index.html                — list of past runs
      run-NN.html               — archived master report for run NN
      run-NN/
        agents/                 — archived per-agent reports for run NN

Run AFTER consolidate_reports.py has run (so reports/bug-report.html exists)
and AFTER all agent artifacts have been downloaded into reports/.
"""
from __future__ import annotations
import json, os, re, shutil, sys
from pathlib import Path
from datetime import datetime

ROOT        = Path(__file__).parent.parent
REPORTS_DIR = ROOT / "reports"
SITE_DIR    = ROOT / "gh-pages-site"
RUN_NUMBER  = os.getenv("GITHUB_RUN_NUMBER", "0")
RUN_URL     = os.getenv("GITHUB_RUN_URL",
                        f"https://github.com/{os.getenv('GITHUB_REPOSITORY','')}/actions/runs/{os.getenv('GITHUB_RUN_ID','')}")
COMMIT_SHA  = (os.getenv("GITHUB_SHA", "") or "")[:7]
COMMIT_MSG  = os.getenv("GITHUB_COMMIT_MESSAGE", "")  # set in workflow


# ─── Per-agent report mapping ─────────────────────────────────────────────────
# Each entry: (custom_source_filename, public_filename, link_label, emoji)
# We prefer the Mehad-styled custom report (`agent-<src>.html`) generated by
# consolidate_reports.py over the default pytest-html outputs which don't
# match our UI design.
AGENT_REPORTS = [
    ("agent-qa01_functional.html",    "qa01-functional.html",   "QA-01 Functional",          "🧪"),
    ("agent-qa02_edge.html",          "qa02-edge.html",         "QA-02 Edge Cases",          "🔍"),
    ("agent-qa03_security.html",      "qa03-security.html",     "QA-03 Security",            "🔒"),
    ("agent-qa04_performance.html",   "qa04-performance.html",  "QA-04 Performance",         "⚡"),
    ("agent-qa05_hallucination.html", "qa05-hallucination.html","QA-05 Hallucination/Data",  "🧠"),
    ("agent-qa06_api.html",           "qa06-api.html",          "QA-06 API & Network",       "🌐"),
    ("agent-qa07_accessibility.html", "qa07-accessibility.html","QA-07 Accessibility",       "♿"),
    ("agent-qa08_mobile.html",        "qa08-mobile.html",       "QA-08 Mobile / Viewport",   "📱"),
    ("agent-qa09_seo.html",           "qa09-seo.html",          "QA-09 SEO & Meta",          "🔎"),
    ("agent-qa10_i18n.html",          "qa10-i18n.html",         "QA-10 i18n & RTL",          "🌏"),
    ("agent-qa11_visual.html",          "qa11-visual.html",          "QA-11 Visual Regression",   "🎨"),
    ("agent-qa12_js_errors.html",       "qa12-js-errors.html",       "QA-12 JS Error Sweeper",    "🐞"),
    ("agent-qa13_security_headers.html","qa13-security-headers.html","QA-13 Security Headers",    "🛡️"),
    ("agent-qa14_cookies.html",         "qa14-cookies.html",         "QA-14 Cookie Security",     "🍪"),
    ("agent-qa15_owasp.html",           "qa15-owasp.html",           "QA-15 OWASP Surface",       "🎯"),
    ("agent-qa16_lighthouse.html",      "qa16-lighthouse.html",      "QA-16 Core Web Vitals",     "📊"),
    ("agent-qa17_memory.html",          "qa17-memory.html",          "QA-17 Memory Leak",         "💧"),
    ("agent-qa18_network.html",         "qa18-network.html",         "QA-18 Network Resilience",  "📡"),
    ("agent-qa19_exploratory.html",     "qa19-exploratory.html",     "QA-19 Autonomous Explorer", "🤖"),
    ("agent-qa20_fuzzing.html",         "qa20-fuzzing.html",         "QA-20 Property-Based Fuzz", "🎲"),
    ("agent-qa22_vision.html",          "qa22-vision.html",          "QA-22 Vision-LLM UI Review","👁️"),
    ("agent-login.html",                "ai-test-agent.html",        "AI Test Agent (auto-gen)",  "🛠️"),
]


def _load_summary() -> dict:
    p = REPORTS_DIR / "consolidated_summary.json"
    if not p.exists():
        return {}
    try:
        return json.loads(p.read_text(encoding="utf-8"))
    except Exception:
        return {}


def _has_agent_report(*filenames: str) -> Path | None:
    """Find an agent's html report by trying multiple filename candidates.
    Walks REPORTS_DIR (artifacts may extract under nested subdirs)."""
    for filename in filenames:
        direct = REPORTS_DIR / filename
        if direct.exists():
            return direct
        for hit in REPORTS_DIR.rglob(filename):
            if hit.is_file():
                return hit
    return None


def _existing_history(site: Path) -> list[tuple[int, Path]]:
    """Return [(run_num, path), ...] for historical reports, sorted desc."""
    history_dir = site / "history"
    if not history_dir.exists():
        return []
    out = []
    for p in history_dir.glob("run-*.html"):
        m = re.match(r"run-(\d+)\.html", p.name)
        if m:
            out.append((int(m.group(1)), p))
    out.sort(reverse=True)
    return out


def _stat_box(label: str, value, klass: str, link_hash: str = "") -> str:
    """Build one stat card. If link_hash is set, the card is a link to
    report.html#<hash> which auto-applies the matching filter."""
    if link_hash:
        return (f'<a class="stat {klass}" href="report.html{link_hash}">'
                f'<div class="lbl">{label}</div>'
                f'<div class="val">{value}</div></a>')
    return (f'<div class="stat {klass}">'
            f'<div class="lbl">{label}</div>'
            f'<div class="val">{value}</div></div>')


def _agent_card(custom_src: str, public_name: str, label: str, emoji: str) -> str:
    has = _has_agent_report(custom_src, public_name) is not None
    if has:
        return (f'<a class="agent-card" href="agents/{public_name}">'
                f'<div class="emoji">{emoji}</div>'
                f'<div class="lbl">{label}</div>'
                f'<div class="cta">View report →</div></a>')
    return (f'<div class="agent-card disabled" title="Report not generated this run">'
            f'<div class="emoji">{emoji}</div>'
            f'<div class="lbl">{label}</div>'
            f'<div class="cta muted">No data</div></div>')


def _fmt_run_ts(run_num: int, ts_map: dict[int, str]) -> str:
    """Return a human-readable date+time string (12-hour) for a run, or ''."""
    raw = ts_map.get(run_num, "")
    if not raw:
        # Fallback: read mtime of the archived HTML file if it exists on disk
        p = SITE_DIR / "history" / f"run-{run_num}.html"
        if p.exists():
            try:
                raw = datetime.utcfromtimestamp(p.stat().st_mtime).isoformat() + "Z"
            except Exception:
                return ""
    if not raw:
        return ""
    try:
        # Accept both "2025-05-11T12:34:56Z" and "2025-05-11T12:34:56"
        raw = raw.rstrip("Z")
        dt = datetime.fromisoformat(raw)
        return dt.strftime("%b %d, %Y %I:%M %p")   # e.g. "May 11, 2025 12:34 PM"
    except Exception:
        return ""


def _history_table(history: list[tuple[int, Path]], ts_map: dict[int, str] | None = None) -> str:
    if not history:
        return ('<p style="color:#8b949e;text-align:center;padding:30px">'
                'No previous runs archived yet — this is the first deployment.</p>')
    ts_map = ts_map or {}
    visible_rows = []
    hidden_rows = []
    for i, (run_num, _path) in enumerate(history[:50]):
        ts = _fmt_run_ts(run_num, ts_map)
        ts_cell = (f'<span style="color:#8b949e;font-size:12px">{ts}</span>'
                   if ts else '<span style="color:#484f58;font-size:12px">—</span>')
        row = (
            f'<tr><td>Run #{run_num}</td>'
            f'<td>{ts_cell}</td>'
            f'<td><a href="history/run-{run_num}.html">View report</a></td></tr>'
        )
        if i < 5:
            visible_rows.append(row)
        else:
            hidden_rows.append(row)

    hidden_tbody = ""
    see_more_btn = ""
    if hidden_rows:
        hidden_tbody = (
            f'<tbody id="history-extra" style="display:none">{"".join(hidden_rows)}</tbody>'
        )
        see_more_btn = (
            '<div style="text-align:center;margin-top:12px">'
            '<button id="history-toggle-btn" onclick="(function(){'
            'var e=document.getElementById(\'history-extra\');'
            'var b=document.getElementById(\'history-toggle-btn\');'
            'if(e.style.display===\'none\'){'
            'e.style.display=\'\';b.textContent=\'See less ▲\';}'
            'else{e.style.display=\'none\';b.textContent=\'See more ▼\';}'
            '})()" '
            'style="background:#21262d;color:#58a6ff;border:1px solid #30363d;'
            'border-radius:6px;padding:6px 20px;font-size:13px;cursor:pointer;'
            'transition:background 0.2s" '
            'onmouseover="this.style.background=\'#30363d\'" '
            'onmouseout="this.style.background=\'#21262d\'">'
            'See more &#9660;</button></div>'
        )

    return (
        '<table class="history-table">'
        '<thead><tr><th>Run</th><th>Date &amp; Time</th><th>Report</th></tr></thead>'
        f'<tbody>{"".join(visible_rows)}</tbody>'
        f'{hidden_tbody}'
        '</table>'
        f'{see_more_btn}'
    )


def _load_trends() -> dict:
    """Load reports/trends.json — populated by consolidate_reports.py."""
    p = REPORTS_DIR / "trends.json"
    if not p.exists():
        return {}
    try:
        import json as _j
        return _j.loads(p.read_text(encoding="utf-8"))
    except Exception:
        return {}


def _detect_regressions(runs: list[dict]) -> list[str]:
    """Compare the most recent run against the previous one. Returns a
    list of human-readable regression messages."""
    if len(runs) < 2:
        return []
    cur = runs[-1]; prev = runs[-2]
    alerts: list[str] = []

    def _pct(s: str) -> float | None:
        if not s or not s.endswith("%"):
            return None
        try:
            return float(s.rstrip("%"))
        except ValueError:
            return None

    cur_rate, prev_rate = _pct(cur.get("pass_rate", "")), _pct(prev.get("pass_rate", ""))
    if cur_rate is not None and prev_rate is not None:
        delta = cur_rate - prev_rate
        if delta <= -2.0:
            alerts.append(
                f"⚠️ Pass rate dropped {abs(delta):.1f}% "
                f"({prev_rate:.1f}% → {cur_rate:.1f}%) since run #{prev['run_number']}"
            )
    cur_bugs = cur.get("bugs", 0)
    prev_bugs = prev.get("bugs", 0)
    if cur_bugs > prev_bugs + 2:
        alerts.append(
            f"⚠️ Bug count jumped {prev_bugs} → {cur_bugs} "
            f"(+{cur_bugs - prev_bugs} new) since run #{prev['run_number']}"
        )
    cur_failed = cur.get("failed", 0)
    prev_failed = prev.get("failed", 0)
    if cur_failed > prev_failed + 3:
        alerts.append(
            f"⚠️ Failed-test count jumped {prev_failed} → {cur_failed} "
            f"(+{cur_failed - prev_failed}) since run #{prev['run_number']}"
        )
    return alerts


def _trend_chart_html(trends: dict) -> str:
    """SVG sparkline + summary card. Pure-HTML so no external chart library
    needed. Shows last 30 runs of pass-rate + bug-count."""
    runs = trends.get("runs", [])[-30:]
    if not runs:
        return ""

    # Compute pass rate per run as float
    points = []
    for r in runs:
        rate = r.get("pass_rate", "")
        if not (isinstance(rate, str) and rate.endswith("%")):
            continue
        try:
            v = float(rate.rstrip("%"))
        except ValueError:
            continue
        points.append((r["run_number"], v, r.get("failed", 0), r.get("bugs", 0)))

    if not points:
        return ""

    # SVG sparkline for pass rate
    w, h, pad = 720, 110, 24
    inner_w = w - 2 * pad
    inner_h = h - 2 * pad
    n = len(points)
    if n == 1:
        path_d = f"M {pad} {pad + inner_h / 2} L {pad + inner_w} {pad + inner_h / 2}"
        circles = f'<circle cx="{pad + inner_w/2}" cy="{pad + inner_h/2}" r="4" fill="#3fb950"/>'
    else:
        coords = []
        for i, (run_num, rate, failed, bugs) in enumerate(points):
            x = pad + (inner_w * i / (n - 1))
            # Pass rate 0..100 → y inner_h..0
            y = pad + (inner_h * (1 - rate / 100.0))
            coords.append((x, y, run_num, rate, failed, bugs))
        path_d = "M " + " L ".join(f"{x:.1f} {y:.1f}" for x, y, *_ in coords)
        circles = "".join(
            f'<circle cx="{x:.1f}" cy="{y:.1f}" r="3" '
            f'fill="{"#3fb950" if r >= 95 else "#d29922" if r >= 85 else "#f85149"}">'
            f'<title>Run #{rn}: {r:.1f}% pass · {f} failed · {b} bugs</title>'
            f'</circle>'
            for x, y, rn, r, f, b in coords
        )

    last = points[-1]
    last_rate = last[1]
    rate_color = "#3fb950" if last_rate >= 95 else "#d29922" if last_rate >= 85 else "#f85149"

    alerts = _detect_regressions(runs)
    alerts_html = ""
    if alerts:
        items = "".join(f'<li>{a}</li>' for a in alerts)
        alerts_html = f"""
<div class="trend-alerts">
  <div class="trend-alerts-title">📉 Regression alerts</div>
  <ul>{items}</ul>
</div>"""

    return f"""
<h2>📊 Trend ({len(points)} run(s))</h2>
<div class="trend-card">
  <div class="trend-summary">
    <div>
      <div class="trend-label">Latest pass rate</div>
      <div class="trend-value" style="color:{rate_color}">{last_rate:.1f}%</div>
    </div>
    <div>
      <div class="trend-label">Latest run</div>
      <div class="trend-value">#{last[0]}</div>
    </div>
    <div>
      <div class="trend-label">Total failures</div>
      <div class="trend-value">{last[2]}</div>
    </div>
    <div>
      <div class="trend-label">Bug tickets</div>
      <div class="trend-value">{last[3]}</div>
    </div>
  </div>
  <svg viewBox="0 0 {w} {h}" class="trend-svg" preserveAspectRatio="none">
    <line x1="{pad}" y1="{pad + inner_h * 0.05}" x2="{pad + inner_w}" y2="{pad + inner_h * 0.05}" stroke="#30363d" stroke-dasharray="2,2"/>
    <line x1="{pad}" y1="{pad + inner_h * 0.5}"  x2="{pad + inner_w}" y2="{pad + inner_h * 0.5}" stroke="#30363d" stroke-dasharray="2,2"/>
    <text x="{pad - 4}" y="{pad + inner_h * 0.05 + 4}" fill="#8b949e" font-size="10" text-anchor="end">100%</text>
    <text x="{pad - 4}" y="{pad + inner_h * 0.5 + 4}" fill="#8b949e" font-size="10" text-anchor="end">50%</text>
    <text x="{pad - 4}" y="{pad + inner_h + 2}" fill="#8b949e" font-size="10" text-anchor="end">0%</text>
    <path d="{path_d}" fill="none" stroke="#58a6ff" stroke-width="2"/>
    {circles}
  </svg>
  {alerts_html}
</div>"""


def _build_index_html(summary: dict, history: list[tuple[int, Path]]) -> str:
    p   = summary.get("total_passed", 0)
    f   = summary.get("total_failed", 0)
    t   = summary.get("total_tests", 0)
    rate= summary.get("pass_rate", "—")
    bugs= summary.get("total_bugs", 0)
    sources = summary.get("sources", [])
    base_url = summary.get("base_url", "")
    when = summary.get("timestamp", "")
    when_short = when[:19].replace("T", " ") if when else ""

    rate_klass = "pass" if (isinstance(rate, str) and rate.endswith("%")
                            and float(rate.rstrip("%")) >= 95) else "warn"

    stats_html = (
        _stat_box("Passed",     p,             "pass",       "#passed") +
        _stat_box("Failed",     f,             "fail" if f else "ok", "#failed") +
        _stat_box("Total Tests", t,            "total",      "#all-tests") +
        _stat_box("Pass Rate",  rate,          rate_klass,   "#tests") +
        _stat_box("Bug Tickets", bugs,         "fail" if bugs else "ok", "#bugs") +
        _stat_box("Sources",    len(sources),  "total",      "#summary-table")
    )
    agent_grid = "".join(_agent_card(src, pub, lbl, em)
                         for src, pub, lbl, em in AGENT_REPORTS)

    trends = _load_trends()
    ts_map: dict[int, str] = {
        int(r["run_number"]): r.get("timestamp", "")
        for r in trends.get("runs", [])
        if r.get("run_number") and r.get("timestamp")
    }
    history_html = _history_table(history, ts_map)
    trend_html   = _trend_chart_html(trends)

    pass_rate_f = 0.0
    try:
        pass_rate_f = float(str(rate).rstrip("%")) if rate and rate != "—" else 0.0
    except (ValueError, TypeError):
        pass
    ring_r = 18
    circ = round(2 * 3.14159 * ring_r, 1)
    ring_offset = round(circ * (1 - pass_rate_f / 100), 2)
    ring_color = ("oklch(0.85 0.14 155)" if pass_rate_f >= 80
                  else "oklch(0.92 0.14 85)" if pass_rate_f >= 50
                  else "oklch(0.85 0.18 25)")

    return f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8"/>
<meta name="viewport" content="width=device-width,initial-scale=1"/>
<title>Mehad QA — Run #{RUN_NUMBER}</title>
<link rel="preconnect" href="https://fonts.googleapis.com"/>
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin/>
<link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&family=JetBrains+Mono:wght@400;600&family=Instrument+Serif:ital@0;1&display=swap" rel="stylesheet"/>
<style>
:root{{
  --bg-0:#07080b;--bg-1:#0c0e13;--bg-2:#11141b;--bg-3:#181c26;
  --ink-0:#f6f7fa;--ink-1:#cdd1de;--ink-2:#9aa0b4;--ink-3:#626880;--ink-4:#3a4154;
  --accent:oklch(0.85 0.18 95);
  --ok:oklch(0.78 0.16 155);--bad:oklch(0.72 0.20 25);--warn:oklch(0.82 0.14 70);
  --font:'Inter',system-ui,sans-serif;
  --mono:'JetBrains Mono',monospace;
  --serif:'Instrument Serif',Georgia,serif;
}}
*,*::before,*::after{{box-sizing:border-box;margin:0;padding:0}}
html{{scroll-behavior:smooth;overflow-x:clip}}
body{{
  background:var(--bg-0);color:var(--ink-1);font-family:var(--font);
  font-size:14px;line-height:1.6;-webkit-font-smoothing:antialiased;
  background-image:
    radial-gradient(ellipse 900px 460px at 14% -10%,oklch(0.85 0.18 95 / 0.06),transparent 60%),
    radial-gradient(ellipse 700px 500px at 92% 6%,oklch(0.72 0.18 295 / 0.06),transparent 65%);
  background-attachment:fixed;
}}
a{{color:var(--accent);text-decoration:none}}
a:hover{{text-decoration:underline}}

/* ── Nav ── */
.nav{{
  position:sticky;top:0;z-index:100;
  background:rgba(7,8,11,0.85);backdrop-filter:blur(12px);
  border-bottom:1px solid var(--ink-4);
  padding:0 28px;display:flex;align-items:center;gap:16px;height:52px;
}}
.mark{{
  width:28px;height:28px;border-radius:7px;flex-shrink:0;
  background:conic-gradient(from 135deg,oklch(0.85 0.18 95),oklch(0.78 0.16 155),oklch(0.72 0.20 25),oklch(0.85 0.18 95));
  display:flex;align-items:center;justify-content:center;
  font-weight:700;font-size:12px;color:#07080b;font-family:var(--mono);
}}
.nav-title{{font-size:14px;font-weight:600;color:var(--ink-0);flex:1}}
.nav-sub{{font-family:var(--mono);font-size:11px;color:var(--ink-3)}}
.btn{{
  border:1px solid var(--ink-4);background:var(--bg-2);color:var(--ink-1);
  padding:6px 14px;border-radius:7px;cursor:pointer;font-size:12px;font-weight:500;
  font-family:var(--font);transition:background .15s;text-decoration:none;
  display:inline-flex;align-items:center;gap:6px;
}}
.btn:hover{{background:var(--bg-3);border-color:var(--ink-2);text-decoration:none}}
.btn.primary{{background:var(--accent);color:var(--bg-0);border-color:var(--accent);font-weight:600}}
.btn.primary:hover{{background:oklch(0.9 0.18 95)}}

/* ── Wrap ── */
.wrap{{max-width:1200px;margin:0 auto;padding:32px 28px 80px}}

/* ── Run header ── */
.run-header{{
  display:grid;grid-template-columns:1fr auto;gap:32px;
  padding-bottom:28px;border-bottom:1px solid var(--ink-4);margin-bottom:28px;
  align-items:start;
}}
.pill{{
  display:inline-flex;align-items:center;gap:6px;padding:3px 10px;
  border-radius:999px;font-family:var(--mono);font-size:11px;font-weight:500;
  border:1px solid var(--ink-4);background:var(--bg-2);color:var(--ink-1);
}}
.pill.run{{background:var(--accent);color:var(--bg-0);border-color:var(--accent);font-weight:700}}
.pill.ok{{background:oklch(0.78 0.16 155 / .15);border-color:oklch(0.78 0.16 155 / .4);color:oklch(0.85 0.14 155)}}
.pill.fail{{background:oklch(0.72 0.20 25 / .15);border-color:oklch(0.72 0.20 25 / .4);color:oklch(0.85 0.18 25)}}
.badge-row{{display:flex;gap:8px;align-items:center;margin-bottom:14px;flex-wrap:wrap}}
.run-header h1{{
  font-family:var(--serif);font-style:italic;font-size:34px;font-weight:400;
  letter-spacing:-.02em;line-height:1.2;color:var(--ink-0);margin:0;
}}
.run-meta{{
  display:flex;gap:16px;flex-wrap:wrap;margin-top:14px;
  font-family:var(--mono);font-size:12px;color:var(--ink-3);
}}
.run-meta a{{color:var(--ink-2)}}
.stamp{{
  border:1.5px solid oklch(0.72 0.20 25 / .6);border-radius:14px;
  padding:16px 20px;min-width:190px;text-align:right;
  background:linear-gradient(180deg,oklch(0.72 0.20 25 / .14),oklch(0.72 0.20 25 / .04));
  position:relative;overflow:hidden;
}}
.stamp.pass-stamp{{
  border-color:oklch(0.78 0.16 155 / .6);
  background:linear-gradient(180deg,oklch(0.78 0.16 155 / .14),oklch(0.78 0.16 155 / .04));
}}
.stamp .k{{font-family:var(--mono);font-size:10px;letter-spacing:.16em;text-transform:uppercase;color:oklch(0.85 0.16 25);font-weight:600}}
.stamp.pass-stamp .k{{color:oklch(0.85 0.14 155)}}
.stamp .v{{font-family:var(--serif);font-style:italic;font-size:36px;line-height:1.1;color:oklch(0.88 0.18 25);margin-top:4px}}
.stamp.pass-stamp .v{{color:oklch(0.85 0.14 155)}}
.stamp .sub{{font-size:12px;color:var(--ink-2);margin-top:4px;font-family:var(--mono)}}

/* ── Stats row ── */
.stats{{
  display:grid;grid-template-columns:repeat(auto-fit,minmax(140px,1fr));
  gap:12px;margin-bottom:28px;
}}
.stat{{
  background:var(--bg-1);border:1px solid var(--ink-4);border-radius:12px;
  padding:18px 16px;position:relative;
  text-decoration:none;color:inherit;display:block;
  transition:transform .12s,border-color .12s,background .12s;
}}
a.stat:hover{{border-color:var(--accent);background:var(--bg-2);transform:translateY(-2px)}}
.stat .lbl{{font-family:var(--mono);font-size:10px;text-transform:uppercase;letter-spacing:.08em;color:var(--ink-3);margin-bottom:8px}}
.stat .val{{font-family:var(--serif);font-style:italic;font-size:34px;font-weight:400;line-height:1;color:var(--ink-0)}}
.stat.pass .val{{color:oklch(0.85 0.14 155)}}
.stat.fail .val{{color:oklch(0.85 0.18 25)}}
.stat.warn .val{{color:oklch(0.92 0.14 85)}}
.stat.ok .val{{color:oklch(0.85 0.14 155)}}
.stat.total .val{{color:var(--accent)}}

/* ── CTA ── */
.primary-cta{{
  display:flex;align-items:center;justify-content:space-between;
  padding:20px 24px;background:var(--bg-1);border:1px solid var(--ink-4);
  border-radius:14px;color:var(--ink-0);text-decoration:none;font-size:15px;
  font-weight:600;margin-bottom:28px;transition:background .15s,border-color .15s;
  gap:16px;
}}
.primary-cta:hover{{background:var(--bg-2);border-color:var(--accent);text-decoration:none}}
.primary-cta .cta-label{{display:flex;align-items:center;gap:12px}}
.primary-cta .cta-sub{{font-size:12px;font-weight:400;color:var(--ink-2);margin-top:3px}}
.primary-cta .cta-arrow{{font-size:20px;color:var(--accent);flex-shrink:0}}

/* ── Section headers ── */
.sec-h{{
  font-family:var(--mono);font-size:11px;letter-spacing:.14em;text-transform:uppercase;
  color:var(--ink-3);font-weight:600;margin:32px 0 14px;
  display:flex;align-items:center;gap:12px;
}}
.sec-h::after{{content:"";flex:1;height:1px;background:var(--ink-4)}}

/* ── Ring ── */
.ring-wrap{{
  background:var(--bg-1);border:1px solid var(--ink-4);border-radius:14px;
  padding:20px 24px;margin-bottom:28px;
  display:flex;align-items:center;gap:20px;
}}
.ring{{flex-shrink:0}}
.ring-info .big{{font-family:var(--serif);font-style:italic;font-size:20px;color:var(--ink-0);letter-spacing:-.01em}}
.ring-info .sm{{font-family:var(--mono);font-size:11px;color:var(--ink-3);margin-top:4px}}

/* ── Agent grid ── */
.agent-grid{{
  display:grid;grid-template-columns:repeat(auto-fit,minmax(220px,1fr));gap:12px;
}}
.agent-card{{
  background:var(--bg-1);border:1px solid var(--ink-4);border-radius:12px;
  padding:18px;text-decoration:none;color:var(--ink-1);display:block;
  transition:transform .12s,border-color .12s,background .12s;
}}
.agent-card:hover{{border-color:var(--accent);background:var(--bg-2);transform:translateY(-2px);text-decoration:none}}
.agent-card.disabled{{opacity:.45;cursor:not-allowed}}
.agent-card .emoji{{font-size:26px;margin-bottom:8px}}
.agent-card .lbl{{font-weight:600;font-size:13.5px;color:var(--ink-0);margin-bottom:4px}}
.agent-card .cta{{font-family:var(--mono);font-size:11px;color:var(--accent)}}
.agent-card .cta.muted{{color:var(--ink-4)}}

/* ── Trend card ── */
.trend-card{{background:var(--bg-1);border:1px solid var(--ink-4);border-radius:12px;padding:18px 22px;margin:0 0 28px}}
.trend-summary{{display:grid;grid-template-columns:repeat(auto-fit,minmax(120px,1fr));gap:16px;margin-bottom:14px}}
.trend-label{{font-family:var(--mono);font-size:10px;color:var(--ink-3);text-transform:uppercase;letter-spacing:.08em}}
.trend-value{{font-family:var(--serif);font-style:italic;font-size:26px;font-weight:400;color:var(--ink-0);margin-top:2px}}
.trend-svg{{width:100%;height:120px;display:block}}
.trend-alerts{{margin-top:14px;padding:12px 16px;background:oklch(0.72 0.20 25 / .12);border-left:3px solid oklch(0.85 0.18 25);border-radius:6px}}
.trend-alerts-title{{font-weight:700;color:oklch(0.85 0.18 25);margin-bottom:6px;font-size:13px}}
.trend-alerts ul{{margin:0;padding-left:18px;color:var(--ink-1);font-size:12px}}
.trend-alerts li{{margin:3px 0}}

/* ── History table ── */
.history-table{{width:100%;border-collapse:collapse;background:var(--bg-1);border:1px solid var(--ink-4);border-radius:12px;overflow:hidden}}
.history-table th,.history-table td{{padding:11px 18px;text-align:left;border-bottom:1px solid var(--ink-4);font-size:13px}}
.history-table th{{background:var(--bg-2);font-family:var(--mono);font-size:10px;text-transform:uppercase;letter-spacing:.08em;color:var(--ink-3)}}
.history-table tr:last-child td{{border-bottom:none}}
.history-table tr:hover td{{background:var(--bg-2)}}
.history-table a{{color:var(--accent)}}

/* ── Footer ── */
.brand-foot{{
  margin-top:56px;padding-top:32px;border-top:1px solid var(--ink-4);
  display:grid;grid-template-columns:1.6fr 1fr 1fr 1fr;gap:40px;
  color:var(--ink-2);font-size:12.5px;
}}
.brand-foot h5{{margin:0 0 12px;color:var(--ink-3);font-family:var(--mono);font-size:10.5px;text-transform:uppercase;letter-spacing:.14em;font-weight:500}}
.brand-foot .who b{{color:var(--ink-0);font-weight:600;display:block;font-size:15px}}
.brand-foot .who span{{display:block;margin-top:2px}}
.brand-foot .who p{{margin:12px 0 0;color:var(--ink-3);max-width:44ch;font-size:12px;line-height:1.6}}
.brand-foot .links{{display:flex;flex-direction:column;gap:10px}}
.brand-foot .links a{{color:var(--ink-2);transition:120ms ease}}
.brand-foot .links a:hover{{color:var(--ink-0)}}

/* ── Responsive ── */
@media (max-width:900px){{
  .brand-foot{{grid-template-columns:1fr 1fr;gap:32px}}
  .run-header{{grid-template-columns:1fr}}
  .stamp{{justify-self:start;min-width:0;width:100%;text-align:left}}
}}
@media (max-width:680px){{
  .wrap{{padding:18px 14px 60px}}
  .nav{{padding:0 14px}}
  .stats{{grid-template-columns:repeat(2,1fr);gap:8px}}
  .stat .val{{font-size:26px}}
  .run-header h1{{font-size:26px}}
  .agent-grid{{grid-template-columns:1fr}}
  .brand-foot{{grid-template-columns:1fr;gap:24px;margin-top:40px}}
  .primary-cta{{flex-direction:column;gap:8px}}
  .trend-summary{{grid-template-columns:repeat(2,1fr)}}
}}
@media (max-width:420px){{
  .stats{{grid-template-columns:1fr}}
  .history-table th,.history-table td{{padding:8px 12px;font-size:11px}}
}}
</style>
</head>
<body>

<!-- Nav -->
<nav class="nav">
  <div class="mark">M</div>
  <div class="nav-title">Mehad QA</div>
  <span class="nav-sub">Run #{RUN_NUMBER} · {when_short or 'latest'}</span>
  <a class="btn primary" href="report.html">Full Report →</a>
</nav>

<div class="wrap">

<!-- Run header -->
<div class="run-header">
  <div>
    <div class="badge-row">
      <span class="pill run">Run #{RUN_NUMBER}</span>
      <span class="pill {'ok' if pass_rate_f >= 80 else 'fail'}">{'Ready' if pass_rate_f >= 95 else 'Review' if f == 0 else 'Needs attention'}</span>
    </div>
    <h1>{'All tests passing' if f == 0 and t > 0 else (str(rate) + ' pass rate') if t > 0 else 'Mehad Autonomous QA'}</h1>
    <div class="run-meta">
      <span>Target: <a href="{base_url}" target="_blank" rel="noopener">{base_url or '—'}</a></span>
      <span>Commit: <a href="https://github.com/{os.getenv('GITHUB_REPOSITORY','')}/commit/{os.getenv('GITHUB_SHA','')}">{COMMIT_SHA or '—'}</a></span>
      <span>Generated: {when_short or '—'}</span>
      <span><a href="{RUN_URL}">CI run ↗</a></span>
    </div>
  </div>
  <div class="stamp {'pass-stamp' if pass_rate_f >= 80 else ''}">
    <div class="k">QA Verdict</div>
    <div class="v">{'Ready' if f == 0 and t > 0 else 'Review' if pass_rate_f >= 80 else 'No-Go'}</div>
    <div class="sub">{rate} pass rate · {bugs} bug(s)</div>
  </div>
</div>

<!-- Stats -->
<div class="stats">{stats_html}</div>

<!-- Ring + CTA -->
<div class="ring-wrap">
  <div class="ring">
    <svg width="80" height="80" viewBox="0 0 44 44">
      <circle cx="22" cy="22" r="{ring_r}" fill="none" stroke="var(--bg-3)" stroke-width="5"/>
      <circle cx="22" cy="22" r="{ring_r}" fill="none" stroke="{ring_color}" stroke-width="5"
        stroke-dasharray="{circ}" stroke-dashoffset="{ring_offset}"
        stroke-linecap="round" transform="rotate(-90 22 22)"/>
      <text x="22" y="25" text-anchor="middle" font-size="8" font-weight="700"
        fill="{ring_color}" font-family="'JetBrains Mono',monospace">{rate}</text>
    </svg>
  </div>
  <div class="ring-info">
    <div class="big">{p} / {t} tests passed</div>
    <div class="sm">{f} failure(s) · {bugs} bug ticket(s) · {len(sources)} source(s)</div>
  </div>
  <a class="btn primary" href="report.html" style="margin-left:auto">View full report →</a>
</div>

<a class="primary-cta" href="report.html">
  <div class="cta-label">
    <span style="font-size:22px">📊</span>
    <div>
      Full bug report
      <div class="cta-sub">Every test · every bug · screenshots · friendly explanations</div>
    </div>
  </div>
  <span class="cta-arrow">→</span>
</a>

{trend_html}

<div class="sec-h">Per-Agent Reports</div>
<p style="color:var(--ink-3);font-family:var(--mono);font-size:12px;margin:0 0 16px">
  {len(AGENT_REPORTS)} specialised AI agents · click any card to see that agent's results
</p>
<div class="agent-grid">{agent_grid}</div>

<div class="sec-h">History</div>
<p style="color:var(--ink-3);font-family:var(--mono);font-size:12px;margin:0 0 14px">
  Past runs are archived — compare against earlier baselines
</p>
{history_html}

<!-- Footer -->
<footer class="brand-foot">
  <div class="who">
    <h5>Built by</h5>
    <b>Mejbaur Bahar Fagun</b>
    <span style="color:var(--ink-1)">Senior Software Engineer QA (IV) · Markopolo.ai</span>
    <p>Mehad Autonomous QA Platform · {len(AGENT_REPORTS)} specialised agents · AI-driven intent-based testing · Playwright + local LLM inference.</p>
  </div>
  <div>
    <h5>Report</h5>
    <div class="links">
      <a href="report.html">Full bug report</a>
      <a href="report.html#bugs">Bug tickets</a>
      <a href="report.html#tests">All tests</a>
    </div>
  </div>
  <div>
    <h5>Run #{RUN_NUMBER}</h5>
    <div class="links">
      <a href="{RUN_URL}" target="_blank" rel="noreferrer">CI run ↗</a>
      <a href="history/index.html">All history</a>
      {f'<a href="{base_url}" target="_blank" rel="noreferrer">Target app ↗</a>' if base_url else ''}
    </div>
  </div>
  <div>
    <h5>Connect</h5>
    <div class="links">
      <a href="https://www.linkedin.com/in/mejbaur/" target="_blank" rel="noreferrer">LinkedIn ↗</a>
      <a href="mailto:mejbaur@markopolo.ai">Email ↗</a>
    </div>
  </div>
</footer>

</div><!-- /wrap -->
</body></html>"""


def _archive_dir() -> Path:
    """Per-run archive folder where this run's individual reports go."""
    arc = SITE_DIR / "history" / f"run-{RUN_NUMBER}"
    arc.mkdir(parents=True, exist_ok=True)
    return arc


def main() -> None:
    SITE_DIR.mkdir(exist_ok=True)
    (SITE_DIR / "agents").mkdir(exist_ok=True)
    (SITE_DIR / "history").mkdir(exist_ok=True)
    archive = _archive_dir()

    # 1. Master report at /report.html (and archived copy at /history/run-N.html)
    master = REPORTS_DIR / "bug-report.html"
    if master.exists():
        shutil.copy(master, SITE_DIR / "report.html")
        shutil.copy(master, SITE_DIR / "history" / f"run-{RUN_NUMBER}.html")
        print(f"  ✅ master report → report.html  +  history/run-{RUN_NUMBER}.html")
    else:
        print("  ⚠️  reports/bug-report.html not found — site will have no master report")

    # 1b. Copy the embedded-videos directory so <video src="videos-embed/..."> works.
    videos_embed = REPORTS_DIR / "videos-embed"
    if videos_embed.exists() and any(videos_embed.iterdir()):
        dest_videos = SITE_DIR / "videos-embed"
        if dest_videos.exists():
            shutil.rmtree(dest_videos)
        shutil.copytree(videos_embed, dest_videos)
        # Also copy into archived per-run folder so historical reports keep their videos
        shutil.copytree(videos_embed, archive / "videos-embed")
        n_videos = sum(1 for _ in dest_videos.glob("*.webm"))
        print(f"  ✅ videos-embed/ copied ({n_videos} video(s))")

    # 1c. Persist trends.json on the site root so the next CI run can fetch
    # it via https://<owner>.github.io/<repo>/trends.json — this is what
    # makes cumulative trend tracking actually work across runs.
    trends_src = REPORTS_DIR / "trends.json"
    if trends_src.exists():
        shutil.copy(trends_src, SITE_DIR / "trends.json")
        # Also save a per-run snapshot for historical inspection
        shutil.copy(trends_src, archive / "trends.json")
        print(f"  ✅ trends.json published to site root")

    # 1d. Publish AI test-code cache so the next CI run can reuse generated
    # tests for unchanged specs (skips slow Ollama calls). cache/tests/<slug>.json
    # is fetched at the start of the next run via _restore_cache_from_gh_pages.
    cache_dir = ROOT / "cache" / "tests"
    if cache_dir.exists() and any(cache_dir.iterdir()):
        dest_cache = SITE_DIR / "cache" / "tests"
        if dest_cache.exists():
            shutil.rmtree(dest_cache)
        dest_cache.mkdir(parents=True, exist_ok=True)
        for f in cache_dir.glob("*.json"):
            shutil.copy(f, dest_cache / f.name)
        n = sum(1 for _ in dest_cache.glob("*.json"))
        print(f"  ✅ AI test cache published ({n} spec(s) cached)")

    # 2. Per-agent reports under /agents/ (and archived copy). Prefer the
    #    custom Mehad-styled `agent-<src>.html` over the default pytest-html
    #    output. Fall back to pytest-html only if no custom report exists.
    found_agents = 0
    for custom_src, public_name, _label, _emoji in AGENT_REPORTS:
        src = _has_agent_report(custom_src, public_name)
        if src is not None:
            shutil.copy(src, SITE_DIR / "agents" / public_name)
            (archive / "agents").mkdir(exist_ok=True)
            shutil.copy(src, archive / "agents" / public_name)
            found_agents += 1
    print(f"  ✅ per-agent reports: {found_agents}/{len(AGENT_REPORTS)}")

    # 3. Build index.html
    summary = _load_summary()
    # History sources, in priority order:
    #   (a) trends.json — cumulative across all runs (gh-pages backed),
    #       knows about runs even if their run-N.html was cleaned up
    #   (b) local SITE_DIR/history/run-*.html — files the build script
    #       just emitted or copied into the deploy dir
    #   (c) the current RUN_NUMBER itself (so a fresh first deployment shows up)
    # Then dedupe BY RUN NUMBER (not by Path tuple — Path strings differ
    # between absolute filesystem entries and relative href strings, which
    # was causing duplicate "Run #N" rows to appear).
    history_runs: dict[int, Path] = {}
    for n, p in _existing_history(SITE_DIR):
        history_runs[n] = Path(f"history/run-{n}.html")
    # Pull every run number trends.json knows about
    try:
        trends_path = SITE_DIR / "trends.json"
        if trends_path.exists():
            tdata = json.loads(trends_path.read_text(encoding="utf-8"))
            for entry in tdata.get("history", []) or tdata.get("runs", []):
                n = entry.get("run") or entry.get("run_number")
                if n is not None:
                    try:
                        history_runs.setdefault(int(n),
                                                  Path(f"history/run-{int(n)}.html"))
                    except (TypeError, ValueError):
                        pass
    except Exception as e:
        print(f"  ⚠️  Could not merge trends.json into history: {e}")
    # Always include the current run if its html was emitted
    if (SITE_DIR / "history" / f"run-{RUN_NUMBER}.html").exists():
        try:
            n = int(RUN_NUMBER)
            history_runs[n] = Path(f"history/run-{n}.html")
        except Exception:
            pass
    history = sorted(history_runs.items(), reverse=True)

    (SITE_DIR / "index.html").write_text(
        _build_index_html(summary, history), encoding="utf-8")
    print(f"  ✅ index.html built ({len(history)} runs in history)")

    # 4. History index page (with unified footer)
    # Build ts_map for the history page (same source as index.html)
    _trends_hist = _load_trends()
    _ts_map_hist: dict[int, str] = {
        int(r["run_number"]): r.get("timestamp", "")
        for r in _trends_hist.get("runs", [])
        if r.get("run_number") and r.get("timestamp")
    }
    rows = []
    for run_num, _ in history[:50]:
        ts = _fmt_run_ts(run_num, _ts_map_hist)
        ts_str = (f'<span style="color:#8b949e;font-size:12px;margin-left:10px">'
                  f'🕐 {ts}</span>') if ts else ""
        rows.append(f'<li><a href="run-{run_num}.html">Run #{run_num}</a>{ts_str}</li>')
    (SITE_DIR / "history" / "index.html").write_text(f"""<!DOCTYPE html>
<html><head><meta charset="UTF-8"/>
<meta name="viewport" content="width=device-width,initial-scale=1"/>
<title>Mehad QA — History</title>
<style>
* {{ box-sizing:border-box }}
body{{font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,sans-serif;
     background:#0d1117;color:#e6edf3;padding:32px;max-width:720px;margin:0 auto;
     line-height:1.5}}
h1{{color:#58a6ff;margin-top:0}}
a{{color:#58a6ff;text-decoration:none}}
a:hover{{text-decoration:underline}}
ul{{list-style:none;padding:0}}
li{{padding:10px 12px;border-bottom:1px solid #30363d;border-radius:4px;
   transition:background .12s}}
li:hover{{background:#161b22}}
.footer{{margin-top:44px;padding:24px 12px;text-align:center;
        color:#8b949e;font-size:12px;border-top:1px solid #30363d}}
.footer .contact-card{{display:inline-flex;flex-direction:column;align-items:center;
                      gap:6px;padding:18px 28px;margin:14px auto 0;
                      background:#161b22;border:1px solid #30363d;border-radius:10px}}
.footer .contact-card .name {{font-weight:700;font-size:15px;color:#e6edf3}}
.footer .contact-card .title{{font-size:12px;color:#8b949e}}
.footer .contact-card .links a{{display:inline-block;color:#58a6ff;
                               font-size:12px;padding:5px 14px;margin-top:8px;
                               border:1px solid #30363d;border-radius:6px;
                               background:#0d1117}}
.footer .contact-card .links a:hover{{background:#1c2333;border-color:#58a6ff}}
@media (max-width:480px) {{ body{{padding:16px}} h1{{font-size:22px}} }}
</style></head>
<body>
<h1>QA Report History</h1>
<p><a href="../index.html">← Back to latest</a></p>
<ul>{"".join(rows)}</ul>
<div class="footer">
  <div style="margin-bottom:6px">Built by Mejbaur Bahar Fagun</div>
  <div class="contact-card">
    <div class="name">Mejbaur Bahar Fagun</div>
    <div class="title">Senior Software Engineer QA (IV) · Markopolo.ai</div>
    <div class="links"><a href="https://www.linkedin.com/in/mejbaur/" target="_blank" rel="noopener">💼 LinkedIn</a></div>
  </div>
</div>
</body></html>""", encoding="utf-8")
    print(f"  ✅ history/index.html with {len(history)} entries")

    print(f"\nSite ready at: {SITE_DIR}")
    print(f"Files: {sum(1 for _ in SITE_DIR.rglob('*.html'))} HTML pages")


if __name__ == "__main__":
    main()
