"""
Build the GitHub Pages site directory from a finished CI run's reports.

Layout:
  gh-pages-site/
    index.html                  — landing page with stats + links to everything
    report.html                 — full master consolidated bug report
    agents/
      qa01-functional.html      — per-agent reports (links from index)
      qa02-edge.html
      ...
    history/
      index.html                — list of past runs
      run-NN.html               — archived master report for run NN
      run-NN/
        agents/                 — archived per-agent reports for run NN

Run AFTER consolidate_reports.py has run (so reports/bug-report.html exists)
and AFTER all agent artifacts have been downloaded into reports/.
"""
from __future__ import annotations
import json, os, re, shutil, sys
from pathlib import Path
from datetime import datetime

ROOT        = Path(__file__).parent.parent
REPORTS_DIR = ROOT / "reports"
SITE_DIR    = ROOT / "gh-pages-site"
RUN_NUMBER  = os.getenv("GITHUB_RUN_NUMBER", "0")
RUN_URL     = os.getenv("GITHUB_RUN_URL",
                        f"https://github.com/{os.getenv('GITHUB_REPOSITORY','')}/actions/runs/{os.getenv('GITHUB_RUN_ID','')}")
COMMIT_SHA  = (os.getenv("GITHUB_SHA", "") or "")[:7]
COMMIT_MSG  = os.getenv("GITHUB_COMMIT_MESSAGE", "")  # set in workflow


# ─── Per-agent report mapping ─────────────────────────────────────────────────
# Each entry: (custom_source_filename, public_filename, link_label, emoji)
# We prefer the Mehad-styled custom report (`agent-<src>.html`) generated by
# consolidate_reports.py over the default pytest-html outputs which don't
# match our UI design.
AGENT_REPORTS = [
    ("agent-qa01_functional.html",    "qa01-functional.html",   "QA-01 Functional",          "🧪"),
    ("agent-qa02_edge.html",          "qa02-edge.html",         "QA-02 Edge Cases",          "🔍"),
    ("agent-qa03_security.html",      "qa03-security.html",     "QA-03 Security",            "🔒"),
    ("agent-qa04_performance.html",   "qa04-performance.html",  "QA-04 Performance",         "⚡"),
    ("agent-qa05_hallucination.html", "qa05-hallucination.html","QA-05 Hallucination/Data",  "🧠"),
    ("agent-qa06_api.html",           "qa06-api.html",          "QA-06 API & Network",       "🌐"),
    ("agent-qa07_accessibility.html", "qa07-accessibility.html","QA-07 Accessibility",       "♿"),
    ("agent-qa08_mobile.html",        "qa08-mobile.html",       "QA-08 Mobile / Viewport",   "📱"),
    ("agent-qa09_seo.html",           "qa09-seo.html",          "QA-09 SEO & Meta",          "🔎"),
    ("agent-qa10_i18n.html",          "qa10-i18n.html",         "QA-10 i18n & RTL",          "🌏"),
    ("agent-qa11_visual.html",          "qa11-visual.html",          "QA-11 Visual Regression",   "🎨"),
    ("agent-qa12_js_errors.html",       "qa12-js-errors.html",       "QA-12 JS Error Sweeper",    "🐞"),
    ("agent-qa13_security_headers.html","qa13-security-headers.html","QA-13 Security Headers",    "🛡️"),
    ("agent-qa14_cookies.html",         "qa14-cookies.html",         "QA-14 Cookie Security",     "🍪"),
    ("agent-qa15_owasp.html",           "qa15-owasp.html",           "QA-15 OWASP Surface",       "🎯"),
    ("agent-qa16_lighthouse.html",      "qa16-lighthouse.html",      "QA-16 Core Web Vitals",     "📊"),
    ("agent-qa17_memory.html",          "qa17-memory.html",          "QA-17 Memory Leak",         "💧"),
    ("agent-qa18_network.html",         "qa18-network.html",         "QA-18 Network Resilience",  "📡"),
    ("agent-qa19_exploratory.html",     "qa19-exploratory.html",     "QA-19 Autonomous Explorer", "🤖"),
    ("agent-qa20_fuzzing.html",         "qa20-fuzzing.html",         "QA-20 Property-Based Fuzz", "🎲"),
    ("agent-qa22_vision.html",          "qa22-vision.html",          "QA-22 Vision-LLM UI Review","👁️"),
    ("agent-login.html",                "ai-test-agent.html",        "AI Test Agent (auto-gen)",  "🛠️"),
    ("e2e-create-book-verify.html",     "e2e-create-book-verify.html","E2E Create+Book+Verify (8-point)","🔄"),
    ("data-flow-e2e.html",              "data-flow-e2e.html",        "DF-E2E Data Flow (8 modules)","📊"),
    ("realtime-data-flow.html",         "realtime-data-flow.html",   "DF-RT Real-Time Booking",   "📡"),
]


def _load_summary() -> dict:
    p = REPORTS_DIR / "consolidated_summary.json"
    if not p.exists():
        return {}
    try:
        return json.loads(p.read_text(encoding="utf-8"))
    except Exception:
        return {}


def _has_agent_report(*filenames: str) -> Path | None:
    """Find an agent's html report by trying multiple filename candidates.
    Walks REPORTS_DIR (artifacts may extract under nested subdirs)."""
    for filename in filenames:
        direct = REPORTS_DIR / filename
        if direct.exists():
            return direct
        for hit in REPORTS_DIR.rglob(filename):
            if hit.is_file():
                return hit
    return None


def _existing_history(site: Path) -> list[tuple[int, Path]]:
    """Return [(run_num, path), ...] for historical reports, sorted desc."""
    history_dir = site / "history"
    if not history_dir.exists():
        return []
    out = []
    for p in history_dir.glob("run-*.html"):
        m = re.match(r"run-(\d+)\.html", p.name)
        if m:
            out.append((int(m.group(1)), p))
    out.sort(reverse=True)
    return out


def _stat_box(label: str, value, klass: str, link_hash: str = "") -> str:
    """Build one stat card. If link_hash is set, the card is a link to
    report.html#<hash> which auto-applies the matching filter."""
    if link_hash:
        return (f'<a class="stat {klass}" href="report.html{link_hash}">'
                f'<div class="lbl">{label}</div>'
                f'<div class="val">{value}</div></a>')
    return (f'<div class="stat {klass}">'
            f'<div class="lbl">{label}</div>'
            f'<div class="val">{value}</div></div>')


def _agent_card(custom_src: str, public_name: str, label: str, emoji: str) -> str:
    has = _has_agent_report(custom_src, public_name) is not None
    if has:
        return (f'<a class="agent-card" href="agents/{public_name}">'
                f'<div class="emoji">{emoji}</div>'
                f'<div class="lbl">{label}</div>'
                f'<div class="cta">View report →</div></a>')
    return (f'<div class="agent-card disabled" title="Report not generated this run">'
            f'<div class="emoji">{emoji}</div>'
            f'<div class="lbl">{label}</div>'
            f'<div class="cta muted">No data</div></div>')


def _fmt_run_ts(run_num: int, ts_map: dict[int, str]) -> str:
    """Return a human-readable date+time string (12-hour) for a run, or ''."""
    raw = ts_map.get(run_num, "")
    if not raw:
        # Fallback: read mtime of the archived HTML file if it exists on disk
        p = SITE_DIR / "history" / f"run-{run_num}.html"
        if p.exists():
            try:
                raw = datetime.utcfromtimestamp(p.stat().st_mtime).isoformat() + "Z"
            except Exception:
                return ""
    if not raw:
        return ""
    try:
        # Accept both "2025-05-11T12:34:56Z" and "2025-05-11T12:34:56"
        raw = raw.rstrip("Z")
        dt = datetime.fromisoformat(raw)
        return dt.strftime("%b %d, %Y %I:%M %p")   # e.g. "May 11, 2025 12:34 PM"
    except Exception:
        return ""


def _history_table(history: list[tuple[int, Path]], ts_map: dict[int, str] | None = None) -> str:
    if not history:
        return ('<p style="color:#8b949e;text-align:center;padding:30px">'
                'No previous runs archived yet — this is the first deployment.</p>')
    ts_map = ts_map or {}
    visible_rows = []
    hidden_rows = []
    for i, (run_num, _path) in enumerate(history[:50]):
        ts = _fmt_run_ts(run_num, ts_map)
        ts_cell = (f'<span style="color:#8b949e;font-size:12px">{ts}</span>'
                   if ts else '<span style="color:#484f58;font-size:12px">—</span>')
        row = (
            f'<tr><td>Run #{run_num}</td>'
            f'<td>{ts_cell}</td>'
            f'<td><a href="history/run-{run_num}.html">View report</a></td></tr>'
        )
        if i < 5:
            visible_rows.append(row)
        else:
            hidden_rows.append(row)

    hidden_tbody = ""
    see_more_btn = ""
    if hidden_rows:
        hidden_tbody = (
            f'<tbody id="history-extra" style="display:none">{"".join(hidden_rows)}</tbody>'
        )
        see_more_btn = (
            '<div style="text-align:center;margin-top:12px">'
            '<button id="history-toggle-btn" onclick="(function(){'
            'var e=document.getElementById(\'history-extra\');'
            'var b=document.getElementById(\'history-toggle-btn\');'
            'if(e.style.display===\'none\'){'
            'e.style.display=\'\';b.textContent=\'See less ▲\';}'
            'else{e.style.display=\'none\';b.textContent=\'See more ▼\';}'
            '})()" '
            'style="background:#21262d;color:#58a6ff;border:1px solid #30363d;'
            'border-radius:6px;padding:6px 20px;font-size:13px;cursor:pointer;'
            'transition:background 0.2s" '
            'onmouseover="this.style.background=\'#30363d\'" '
            'onmouseout="this.style.background=\'#21262d\'">'
            'See more &#9660;</button></div>'
        )

    return (
        '<table class="history-table">'
        '<thead><tr><th>Run</th><th>Date &amp; Time</th><th>Report</th></tr></thead>'
        f'<tbody>{"".join(visible_rows)}</tbody>'
        f'{hidden_tbody}'
        '</table>'
        f'{see_more_btn}'
    )


def _load_trends() -> dict:
    """Load reports/trends.json — populated by consolidate_reports.py."""
    p = REPORTS_DIR / "trends.json"
    if not p.exists():
        return {}
    try:
        import json as _j
        return _j.loads(p.read_text(encoding="utf-8"))
    except Exception:
        return {}


def _detect_regressions(runs: list[dict]) -> list[str]:
    """Compare the most recent run against the previous one. Returns a
    list of human-readable regression messages."""
    if len(runs) < 2:
        return []
    cur = runs[-1]; prev = runs[-2]
    alerts: list[str] = []

    def _pct(s: str) -> float | None:
        if not s or not s.endswith("%"):
            return None
        try:
            return float(s.rstrip("%"))
        except ValueError:
            return None

    cur_rate, prev_rate = _pct(cur.get("pass_rate", "")), _pct(prev.get("pass_rate", ""))
    if cur_rate is not None and prev_rate is not None:
        delta = cur_rate - prev_rate
        if delta <= -2.0:
            alerts.append(
                f"⚠️ Pass rate dropped {abs(delta):.1f}% "
                f"({prev_rate:.1f}% → {cur_rate:.1f}%) since run #{prev['run_number']}"
            )
    cur_bugs = cur.get("bugs", 0)
    prev_bugs = prev.get("bugs", 0)
    if cur_bugs > prev_bugs + 2:
        alerts.append(
            f"⚠️ Bug count jumped {prev_bugs} → {cur_bugs} "
            f"(+{cur_bugs - prev_bugs} new) since run #{prev['run_number']}"
        )
    cur_failed = cur.get("failed", 0)
    prev_failed = prev.get("failed", 0)
    if cur_failed > prev_failed + 3:
        alerts.append(
            f"⚠️ Failed-test count jumped {prev_failed} → {cur_failed} "
            f"(+{cur_failed - prev_failed}) since run #{prev['run_number']}"
        )
    return alerts


def _trend_chart_html(trends: dict) -> str:
    """SVG sparkline + summary card. Pure-HTML so no external chart library
    needed. Shows last 30 runs of pass-rate + bug-count."""
    runs = trends.get("runs", [])[-30:]
    if not runs:
        return ""

    # Compute pass rate per run as float
    points = []
    for r in runs:
        rate = r.get("pass_rate", "")
        if not (isinstance(rate, str) and rate.endswith("%")):
            continue
        try:
            v = float(rate.rstrip("%"))
        except ValueError:
            continue
        points.append((r["run_number"], v, r.get("failed", 0), r.get("bugs", 0)))

    if not points:
        return ""

    # SVG sparkline for pass rate
    w, h, pad = 720, 110, 24
    inner_w = w - 2 * pad
    inner_h = h - 2 * pad
    n = len(points)
    if n == 1:
        path_d = f"M {pad} {pad + inner_h / 2} L {pad + inner_w} {pad + inner_h / 2}"
        circles = f'<circle cx="{pad + inner_w/2}" cy="{pad + inner_h/2}" r="4" fill="#3fb950"/>'
    else:
        coords = []
        for i, (run_num, rate, failed, bugs) in enumerate(points):
            x = pad + (inner_w * i / (n - 1))
            # Pass rate 0..100 → y inner_h..0
            y = pad + (inner_h * (1 - rate / 100.0))
            coords.append((x, y, run_num, rate, failed, bugs))
        path_d = "M " + " L ".join(f"{x:.1f} {y:.1f}" for x, y, *_ in coords)
        circles = "".join(
            f'<circle cx="{x:.1f}" cy="{y:.1f}" r="3" '
            f'fill="{"#3fb950" if r >= 95 else "#d29922" if r >= 85 else "#f85149"}">'
            f'<title>Run #{rn}: {r:.1f}% pass · {f} failed · {b} bugs</title>'
            f'</circle>'
            for x, y, rn, r, f, b in coords
        )

    last = points[-1]
    last_rate = last[1]
    rate_color = "#3fb950" if last_rate >= 95 else "#d29922" if last_rate >= 85 else "#f85149"

    alerts = _detect_regressions(runs)
    alerts_html = ""
    if alerts:
        items = "".join(f'<li>{a}</li>' for a in alerts)
        alerts_html = f"""
<div class="trend-alerts">
  <div class="trend-alerts-title">📉 Regression alerts</div>
  <ul>{items}</ul>
</div>"""

    return f"""
<h2>📊 Trend ({len(points)} run(s))</h2>
<div class="trend-card">
  <div class="trend-summary">
    <div>
      <div class="trend-label">Latest pass rate</div>
      <div class="trend-value" style="color:{rate_color}">{last_rate:.1f}%</div>
    </div>
    <div>
      <div class="trend-label">Latest run</div>
      <div class="trend-value">#{last[0]}</div>
    </div>
    <div>
      <div class="trend-label">Total failures</div>
      <div class="trend-value">{last[2]}</div>
    </div>
    <div>
      <div class="trend-label">Bug tickets</div>
      <div class="trend-value">{last[3]}</div>
    </div>
  </div>
  <svg viewBox="0 0 {w} {h}" class="trend-svg" preserveAspectRatio="none">
    <line x1="{pad}" y1="{pad + inner_h * 0.05}" x2="{pad + inner_w}" y2="{pad + inner_h * 0.05}" stroke="#30363d" stroke-dasharray="2,2"/>
    <line x1="{pad}" y1="{pad + inner_h * 0.5}"  x2="{pad + inner_w}" y2="{pad + inner_h * 0.5}" stroke="#30363d" stroke-dasharray="2,2"/>
    <text x="{pad - 4}" y="{pad + inner_h * 0.05 + 4}" fill="#8b949e" font-size="10" text-anchor="end">100%</text>
    <text x="{pad - 4}" y="{pad + inner_h * 0.5 + 4}" fill="#8b949e" font-size="10" text-anchor="end">50%</text>
    <text x="{pad - 4}" y="{pad + inner_h + 2}" fill="#8b949e" font-size="10" text-anchor="end">0%</text>
    <path d="{path_d}" fill="none" stroke="#58a6ff" stroke-width="2"/>
    {circles}
  </svg>
  {alerts_html}
</div>"""


def _build_index_html(summary: dict, history: list[tuple[int, Path]]) -> str:
    p   = summary.get("total_passed", 0)
    f   = summary.get("total_failed", 0)
    t   = summary.get("total_tests", 0)
    rate= summary.get("pass_rate", "—")
    bugs= summary.get("total_bugs", 0)
    sources = summary.get("sources", [])
    base_url = summary.get("base_url", "")
    when = summary.get("timestamp", "")
    when_short = when[:19].replace("T", " ") if when else ""

    rate_klass = "pass" if (isinstance(rate, str) and rate.endswith("%")
                            and float(rate.rstrip("%")) >= 95) else "warn"

    trends = _load_trends()

    # actual_ran: how many tests actually executed this run (honest denominator).
    # t may be inflated to the HWM suite capacity for display — but
    # pass_rate is already correct in consolidated_summary.json (computed from
    # actual_ran by consolidate_reports.py).
    actual_ran = summary.get("actual_tests_run", t)
    hw_total = trends.get("max_total_tests", 0)
    suite_cap = max(t, hw_total)   # for display in Total Tests card

    # Show "X ran / Y suite" when the suite capacity > actual run count so
    # users immediately know some agent artifacts were missing this run.
    if suite_cap > actual_ran and actual_ran > 0:
        total_label = "Tests Ran / Suite"
        total_value = f"{actual_ran:,} / {suite_cap:,}"
    else:
        total_label = "Total Tests"
        total_value = suite_cap if suite_cap else t

    stats_html = (
        _stat_box("Passed",       p,            "pass",              "#passed") +
        _stat_box("Failed",       f,            "fail" if f else "ok", "#failed") +
        _stat_box(total_label,    total_value,  "total",             "#all-tests") +
        _stat_box("Pass Rate",    rate,         rate_klass,          "#tests") +
        _stat_box("Bug Tickets",  bugs,         "fail" if bugs else "ok", "#bugs") +
        _stat_box("Sources",      len(sources), "total",             "#summary-table")
    )
    agent_grid = "".join(_agent_card(src, pub, lbl, em)
                         for src, pub, lbl, em in AGENT_REPORTS)
    ts_map: dict[int, str] = {
        int(r["run_number"]): r.get("timestamp", "")
        for r in trends.get("runs", [])
        if r.get("run_number") and r.get("timestamp")
    }
    history_html = _history_table(history, ts_map)
    trend_html   = _trend_chart_html(trends)

    pass_rate_f = 0.0
    try:
        pass_rate_f = float(str(rate).rstrip("%")) if rate and rate != "—" else 0.0
    except (ValueError, TypeError):
        pass
    ring_r = 18
    circ = round(2 * 3.14159 * ring_r, 1)
    ring_offset = round(circ * (1 - pass_rate_f / 100), 2)
    ring_color = ("oklch(0.85 0.14 155)" if pass_rate_f >= 80
                  else "oklch(0.92 0.14 85)" if pass_rate_f >= 50
                  else "oklch(0.85 0.18 25)")

    return f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8"/>
<meta name="viewport" content="width=device-width,initial-scale=1"/>
<title>Mehad QA — Run #{RUN_NUMBER}</title>
<link rel="preconnect" href="https://fonts.googleapis.com"/>
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin/>
<link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&family=JetBrains+Mono:wght@400;600&family=Instrument+Serif:ital@0;1&display=swap" rel="stylesheet"/>
<style>
:root{{
  --bg-0:#07080b;--bg-1:#0c0e13;--bg-2:#11141b;--bg-3:#181c26;
  --ink-0:#f6f7fa;--ink-1:#cdd1de;--ink-2:#9aa0b4;--ink-3:#626880;--ink-4:#3a4154;
  --accent:oklch(0.85 0.18 95);
  --ok:oklch(0.78 0.16 155);--bad:oklch(0.72 0.20 25);--warn:oklch(0.82 0.14 70);
  --font:'Inter',system-ui,sans-serif;
  --mono:'JetBrains Mono',monospace;
  --serif:'Instrument Serif',Georgia,serif;
}}
*,*::before,*::after{{box-sizing:border-box;margin:0;padding:0}}
html{{scroll-behavior:smooth;overflow-x:clip}}
body{{
  background:var(--bg-0);color:var(--ink-1);font-family:var(--font);
  font-size:14px;line-height:1.6;-webkit-font-smoothing:antialiased;
  background-image:
    radial-gradient(ellipse 900px 460px at 14% -10%,oklch(0.85 0.18 95 / 0.06),transparent 60%),
    radial-gradient(ellipse 700px 500px at 92% 6%,oklch(0.72 0.18 295 / 0.06),transparent 65%);
  background-attachment:fixed;
}}
a{{color:var(--accent);text-decoration:none}}
a:hover{{text-decoration:underline}}

/* ── Nav ── */
.nav{{
  position:sticky;top:0;z-index:100;
  background:rgba(7,8,11,0.85);backdrop-filter:blur(12px);
  border-bottom:1px solid var(--ink-4);
  padding:0 28px;display:flex;align-items:center;gap:16px;height:52px;
}}
.mark{{
  width:28px;height:28px;border-radius:7px;flex-shrink:0;
  background:conic-gradient(from 135deg,oklch(0.85 0.18 95),oklch(0.78 0.16 155),oklch(0.72 0.20 25),oklch(0.85 0.18 95));
  display:flex;align-items:center;justify-content:center;
  font-weight:700;font-size:12px;color:#07080b;font-family:var(--mono);
}}
.nav-title{{font-size:14px;font-weight:600;color:var(--ink-0);flex:1}}
.nav-sub{{font-family:var(--mono);font-size:11px;color:var(--ink-3)}}
.btn{{
  border:1px solid var(--ink-4);background:var(--bg-2);color:var(--ink-1);
  padding:6px 14px;border-radius:7px;cursor:pointer;font-size:12px;font-weight:500;
  font-family:var(--font);transition:background .15s;text-decoration:none;
  display:inline-flex;align-items:center;gap:6px;
}}
.btn:hover{{background:var(--bg-3);border-color:var(--ink-2);text-decoration:none}}
.btn.primary{{background:var(--accent);color:var(--bg-0);border-color:var(--accent);font-weight:600}}
.btn.primary:hover{{background:oklch(0.9 0.18 95)}}

/* ── Wrap ── */
.wrap{{max-width:1200px;margin:0 auto;padding:32px 28px 80px}}

/* ── Run header ── */
.run-header{{
  display:grid;grid-template-columns:1fr auto;gap:32px;
  padding-bottom:28px;border-bottom:1px solid var(--ink-4);margin-bottom:28px;
  align-items:start;
}}
.pill{{
  display:inline-flex;align-items:center;gap:6px;padding:3px 10px;
  border-radius:999px;font-family:var(--mono);font-size:11px;font-weight:500;
  border:1px solid var(--ink-4);background:var(--bg-2);color:var(--ink-1);
}}
.pill.run{{background:var(--accent);color:var(--bg-0);border-color:var(--accent);font-weight:700}}
.pill.ok{{background:oklch(0.78 0.16 155 / .15);border-color:oklch(0.78 0.16 155 / .4);color:oklch(0.85 0.14 155)}}
.pill.fail{{background:oklch(0.72 0.20 25 / .15);border-color:oklch(0.72 0.20 25 / .4);color:oklch(0.85 0.18 25)}}
.badge-row{{display:flex;gap:8px;align-items:center;margin-bottom:14px;flex-wrap:wrap}}
.run-header h1{{
  font-family:var(--serif);font-style:italic;font-size:34px;font-weight:400;
  letter-spacing:-.02em;line-height:1.2;color:var(--ink-0);margin:0;
}}
.run-meta{{
  display:flex;gap:16px;flex-wrap:wrap;margin-top:14px;
  font-family:var(--mono);font-size:12px;color:var(--ink-3);
}}
.run-meta a{{color:var(--ink-2)}}
.stamp{{
  border:1.5px solid oklch(0.72 0.20 25 / .6);border-radius:14px;
  padding:16px 20px;min-width:190px;text-align:right;
  background:linear-gradient(180deg,oklch(0.72 0.20 25 / .14),oklch(0.72 0.20 25 / .04));
  position:relative;overflow:hidden;
}}
.stamp.pass-stamp{{
  border-color:oklch(0.78 0.16 155 / .6);
  background:linear-gradient(180deg,oklch(0.78 0.16 155 / .14),oklch(0.78 0.16 155 / .04));
}}
.stamp .k{{font-family:var(--mono);font-size:10px;letter-spacing:.16em;text-transform:uppercase;color:oklch(0.85 0.16 25);font-weight:600}}
.stamp.pass-stamp .k{{color:oklch(0.85 0.14 155)}}
.stamp .v{{font-family:var(--serif);font-style:italic;font-size:36px;line-height:1.1;color:oklch(0.88 0.18 25);margin-top:4px}}
.stamp.pass-stamp .v{{color:oklch(0.85 0.14 155)}}
.stamp .sub{{font-size:12px;color:var(--ink-2);margin-top:4px;font-family:var(--mono)}}

/* ── Stats row ── */
.stats{{
  display:grid;grid-template-columns:repeat(auto-fit,minmax(140px,1fr));
  gap:12px;margin-bottom:28px;
}}
.stat{{
  background:var(--bg-1);border:1px solid var(--ink-4);border-radius:12px;
  padding:18px 16px;position:relative;
  text-decoration:none;color:inherit;display:block;
  transition:transform .12s,border-color .12s,background .12s;
}}
a.stat:hover{{border-color:var(--accent);background:var(--bg-2);transform:translateY(-2px)}}
.stat .lbl{{font-family:var(--mono);font-size:10px;text-transform:uppercase;letter-spacing:.08em;color:var(--ink-3);margin-bottom:8px}}
.stat .val{{font-family:var(--serif);font-style:italic;font-size:34px;font-weight:400;line-height:1;color:var(--ink-0)}}
.stat.pass .val{{color:oklch(0.85 0.14 155)}}
.stat.fail .val{{color:oklch(0.85 0.18 25)}}
.stat.warn .val{{color:oklch(0.92 0.14 85)}}
.stat.ok .val{{color:oklch(0.85 0.14 155)}}
.stat.total .val{{color:var(--accent)}}

/* ── CTA ── */
.primary-cta{{
  display:flex;align-items:center;justify-content:space-between;
  padding:20px 24px;background:var(--bg-1);border:1px solid var(--ink-4);
  border-radius:14px;color:var(--ink-0);text-decoration:none;font-size:15px;
  font-weight:600;margin-bottom:28px;transition:background .15s,border-color .15s;
  gap:16px;
}}
.primary-cta:hover{{background:var(--bg-2);border-color:var(--accent);text-decoration:none}}
.primary-cta .cta-label{{display:flex;align-items:center;gap:12px}}
.primary-cta .cta-sub{{font-size:12px;font-weight:400;color:var(--ink-2);margin-top:3px}}
.primary-cta .cta-arrow{{font-size:20px;color:var(--accent);flex-shrink:0}}

/* ── Section headers ── */
.sec-h{{
  font-family:var(--mono);font-size:11px;letter-spacing:.14em;text-transform:uppercase;
  color:var(--ink-3);font-weight:600;margin:32px 0 14px;
  display:flex;align-items:center;gap:12px;
}}
.sec-h::after{{content:"";flex:1;height:1px;background:var(--ink-4)}}

/* ── Ring ── */
.ring-wrap{{
  background:var(--bg-1);border:1px solid var(--ink-4);border-radius:14px;
  padding:20px 24px;margin-bottom:28px;
  display:flex;align-items:center;gap:20px;
}}
.ring{{flex-shrink:0}}
.ring-info .big{{font-family:var(--serif);font-style:italic;font-size:20px;color:var(--ink-0);letter-spacing:-.01em}}
.ring-info .sm{{font-family:var(--mono);font-size:11px;color:var(--ink-3);margin-top:4px}}

/* ── Agent grid ── */
.agent-grid{{
  display:grid;grid-template-columns:repeat(auto-fit,minmax(220px,1fr));gap:12px;
}}
.agent-card{{
  background:var(--bg-1);border:1px solid var(--ink-4);border-radius:12px;
  padding:18px;text-decoration:none;color:var(--ink-1);display:block;
  transition:transform .12s,border-color .12s,background .12s;
}}
.agent-card:hover{{border-color:var(--accent);background:var(--bg-2);transform:translateY(-2px);text-decoration:none}}
.agent-card.disabled{{opacity:.45;cursor:not-allowed}}
.agent-card .emoji{{font-size:26px;margin-bottom:8px}}
.agent-card .lbl{{font-weight:600;font-size:13.5px;color:var(--ink-0);margin-bottom:4px}}
.agent-card .cta{{font-family:var(--mono);font-size:11px;color:var(--accent)}}
.agent-card .cta.muted{{color:var(--ink-4)}}

/* ── Trend card ── */
.trend-card{{background:var(--bg-1);border:1px solid var(--ink-4);border-radius:12px;padding:18px 22px;margin:0 0 28px}}
.trend-summary{{display:grid;grid-template-columns:repeat(auto-fit,minmax(120px,1fr));gap:16px;margin-bottom:14px}}
.trend-label{{font-family:var(--mono);font-size:10px;color:var(--ink-3);text-transform:uppercase;letter-spacing:.08em}}
.trend-value{{font-family:var(--serif);font-style:italic;font-size:26px;font-weight:400;color:var(--ink-0);margin-top:2px}}
.trend-svg{{width:100%;height:120px;display:block}}
.trend-alerts{{margin-top:14px;padding:12px 16px;background:oklch(0.72 0.20 25 / .12);border-left:3px solid oklch(0.85 0.18 25);border-radius:6px}}
.trend-alerts-title{{font-weight:700;color:oklch(0.85 0.18 25);margin-bottom:6px;font-size:13px}}
.trend-alerts ul{{margin:0;padding-left:18px;color:var(--ink-1);font-size:12px}}
.trend-alerts li{{margin:3px 0}}

/* ── History table ── */
.history-table{{width:100%;border-collapse:collapse;background:var(--bg-1);border:1px solid var(--ink-4);border-radius:12px;overflow:hidden}}
.history-table th,.history-table td{{padding:11px 18px;text-align:left;border-bottom:1px solid var(--ink-4);font-size:13px}}
.history-table th{{background:var(--bg-2);font-family:var(--mono);font-size:10px;text-transform:uppercase;letter-spacing:.08em;color:var(--ink-3)}}
.history-table tr:last-child td{{border-bottom:none}}
.history-table tr:hover td{{background:var(--bg-2)}}
.history-table a{{color:var(--accent)}}

/* ── Footer ── */
.brand-foot{{
  margin-top:56px;padding-top:32px;border-top:1px solid var(--ink-4);
  display:grid;grid-template-columns:1.6fr 1fr 1fr 1fr;gap:40px;
  color:var(--ink-2);font-size:12.5px;
}}
.brand-foot h5{{margin:0 0 12px;color:var(--ink-3);font-family:var(--mono);font-size:10.5px;text-transform:uppercase;letter-spacing:.14em;font-weight:500}}
.brand-foot .who b{{color:var(--ink-0);font-weight:600;display:block;font-size:15px}}
.brand-foot .who span{{display:block;margin-top:2px}}
.brand-foot .who p{{margin:12px 0 0;color:var(--ink-3);max-width:44ch;font-size:12px;line-height:1.6}}
.brand-foot .links{{display:flex;flex-direction:column;gap:10px}}
.brand-foot .links a{{color:var(--ink-2);transition:120ms ease}}
.brand-foot .links a:hover{{color:var(--ink-0)}}

/* ── Responsive ── */
@media (max-width:900px){{
  .brand-foot{{grid-template-columns:1fr 1fr;gap:32px}}
  .run-header{{grid-template-columns:1fr}}
  .stamp{{justify-self:start;min-width:0;width:100%;text-align:left}}
}}
@media (max-width:680px){{
  .wrap{{padding:18px 14px 60px}}
  .nav{{padding:0 14px}}
  .stats{{grid-template-columns:repeat(2,1fr);gap:8px}}
  .stat .val{{font-size:26px}}
  .run-header h1{{font-size:26px}}
  .agent-grid{{grid-template-columns:1fr}}
  .brand-foot{{grid-template-columns:1fr;gap:24px;margin-top:40px}}
  .primary-cta{{flex-direction:column;gap:8px}}
  .trend-summary{{grid-template-columns:repeat(2,1fr)}}
}}
@media (max-width:420px){{
  .stats{{grid-template-columns:1fr}}
  .history-table th,.history-table td{{padding:8px 12px;font-size:11px}}
}}
</style>
</head>
<body>

<!-- Nav -->
<nav class="nav">
  <div class="mark">M</div>
  <div class="nav-title">Mehad QA</div>
  <span class="nav-sub">Run #{RUN_NUMBER} · {when_short or 'latest'}</span>
  <a class="btn" href="otp-setup.html">📱 OTP Setup</a>
  <a class="btn primary" href="report.html">Full Report →</a>
</nav>

<div class="wrap">

<!-- Run header -->
<div class="run-header">
  <div>
    <div class="badge-row">
      <span class="pill run">Run #{RUN_NUMBER}</span>
      <span class="pill {'ok' if pass_rate_f >= 80 else 'fail'}">{'Ready' if pass_rate_f >= 95 else 'Review' if f == 0 else 'Needs attention'}</span>
    </div>
    <h1>{'All tests passing' if f == 0 and t > 0 else (str(rate) + ' pass rate') if t > 0 else 'Mehad Autonomous QA'}</h1>
    <div class="run-meta">
      <span>Target: <a href="{base_url}" target="_blank" rel="noopener">{base_url or '—'}</a></span>
      <span>Commit: <a href="https://github.com/{os.getenv('GITHUB_REPOSITORY','')}/commit/{os.getenv('GITHUB_SHA','')}">{COMMIT_SHA or '—'}</a></span>
      <span>Generated: {when_short or '—'}</span>
      <span><a href="{RUN_URL}">CI run ↗</a></span>
    </div>
  </div>
  <div class="stamp {'pass-stamp' if pass_rate_f >= 80 else ''}">
    <div class="k">QA Verdict</div>
    <div class="v">{'Ready' if f == 0 and t > 0 else 'Review' if pass_rate_f >= 80 else 'No-Go'}</div>
    <div class="sub">{rate} pass rate · {bugs} bug(s)</div>
  </div>
</div>

<!-- Stats -->
<div class="stats">{stats_html}</div>

<!-- Ring + CTA -->
<div class="ring-wrap">
  <div class="ring">
    <svg width="80" height="80" viewBox="0 0 44 44">
      <circle cx="22" cy="22" r="{ring_r}" fill="none" stroke="var(--bg-3)" stroke-width="5"/>
      <circle cx="22" cy="22" r="{ring_r}" fill="none" stroke="{ring_color}" stroke-width="5"
        stroke-dasharray="{circ}" stroke-dashoffset="{ring_offset}"
        stroke-linecap="round" transform="rotate(-90 22 22)"/>
      <text x="22" y="25" text-anchor="middle" font-size="8" font-weight="700"
        fill="{ring_color}" font-family="'JetBrains Mono',monospace">{rate}</text>
    </svg>
  </div>
  <div class="ring-info">
    <div class="big">{p} / {actual_ran} tests passed</div>
    <div class="sm">{f} failure(s) · {bugs} bug ticket(s) · {len(sources)} source(s)</div>
  </div>
  <a class="btn primary" href="report.html" style="margin-left:auto">View full report →</a>
</div>

<a class="primary-cta" href="report.html">
  <div class="cta-label">
    <span style="font-size:22px">📊</span>
    <div>
      Full bug report
      <div class="cta-sub">Every test · every bug · screenshots · friendly explanations</div>
    </div>
  </div>
  <span class="cta-arrow">→</span>
</a>

{trend_html}

<div class="sec-h">Tools</div>
<div class="agent-grid" style="margin-bottom:28px">
  <a class="agent-card" href="otp-setup.html">
    <div class="emoji">📱</div>
    <div class="lbl">OTP Phone Setup</div>
    <div class="cta">Configure WhatsApp OTP →</div>
  </a>
</div>

<div class="sec-h">Per-Agent Reports</div>
<p style="color:var(--ink-3);font-family:var(--mono);font-size:12px;margin:0 0 16px">
  {len(AGENT_REPORTS)} specialised AI agents · click any card to see that agent's results
</p>
<div class="agent-grid">{agent_grid}</div>

<div class="sec-h">History</div>
<p style="color:var(--ink-3);font-family:var(--mono);font-size:12px;margin:0 0 14px">
  Past runs are archived — compare against earlier baselines
</p>
{history_html}

<!-- Footer -->
<footer class="brand-foot">
  <div class="who">
    <h5>Built by</h5>
    <b>Mejbaur Bahar Fagun</b>
    <span style="color:var(--ink-1)">Senior Software Engineer QA (IV) · Markopolo.ai</span>
    <p>Mehad Autonomous QA Platform · {len(AGENT_REPORTS)} specialised agents · AI-driven intent-based testing · Playwright + local LLM inference.</p>
  </div>
  <div>
    <h5>Report</h5>
    <div class="links">
      <a href="report.html">Full bug report</a>
      <a href="report.html#bugs">Bug tickets</a>
      <a href="report.html#tests">All tests</a>
      <a href="otp-setup.html">OTP setup guide</a>
    </div>
  </div>
  <div>
    <h5>Run #{RUN_NUMBER}</h5>
    <div class="links">
      <a href="{RUN_URL}" target="_blank" rel="noreferrer">CI run ↗</a>
      <a href="history/index.html">All history</a>
      {f'<a href="{base_url}" target="_blank" rel="noreferrer">Target app ↗</a>' if base_url else ''}
    </div>
  </div>
  <div>
    <h5>Connect</h5>
    <div class="links">
      <a href="https://www.linkedin.com/in/mejbaur/" target="_blank" rel="noreferrer">LinkedIn ↗</a>
      <a href="mailto:mejbaur@markopolo.ai">Email ↗</a>
    </div>
  </div>
</footer>

</div><!-- /wrap -->
</body></html>"""


def _build_otp_setup_html() -> str:
    """Build the OTP phone setup guide page."""
    return r"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8"/>
<meta name="viewport" content="width=device-width,initial-scale=1"/>
<title>Mehad QA — OTP Phone Setup</title>
<link rel="preconnect" href="https://fonts.googleapis.com"/>
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin/>
<link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&family=JetBrains+Mono:wght@400;600&family=Instrument+Serif:ital@0;1&display=swap" rel="stylesheet"/>
<script src="https://cdnjs.cloudflare.com/ajax/libs/qrcodejs/1.0.0/qrcode.min.js" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
<style>
:root{
  --bg-0:#07080b;--bg-1:#0c0e13;--bg-2:#11141b;--bg-3:#181c26;
  --ink-0:#f6f7fa;--ink-1:#cdd1de;--ink-2:#9aa0b4;--ink-3:#626880;--ink-4:#3a4154;
  --accent:oklch(0.85 0.18 95);
  --ok:oklch(0.78 0.16 155);--bad:oklch(0.72 0.20 25);--warn:oklch(0.82 0.14 70);
  --font:'Inter',system-ui,sans-serif;
  --mono:'JetBrains Mono',monospace;
  --serif:'Instrument Serif',Georgia,serif;
}
*,*::before,*::after{box-sizing:border-box;margin:0;padding:0}
html{scroll-behavior:smooth;overflow-x:clip}
body{
  background:var(--bg-0);color:var(--ink-1);font-family:var(--font);
  font-size:14px;line-height:1.6;-webkit-font-smoothing:antialiased;
  background-image:
    radial-gradient(ellipse 900px 460px at 14% -10%,oklch(0.85 0.18 95 / 0.06),transparent 60%),
    radial-gradient(ellipse 700px 500px at 92% 6%,oklch(0.72 0.18 295 / 0.06),transparent 65%);
  background-attachment:fixed;
}
a{color:var(--accent);text-decoration:none}
a:hover{text-decoration:underline}
.nav{
  position:sticky;top:0;z-index:100;
  background:rgba(7,8,11,0.85);backdrop-filter:blur(12px);
  border-bottom:1px solid var(--ink-4);
  padding:0 28px;display:flex;align-items:center;gap:16px;height:52px;
}
.mark{
  width:28px;height:28px;border-radius:7px;flex-shrink:0;
  background:conic-gradient(from 135deg,oklch(0.85 0.18 95),oklch(0.78 0.16 155),oklch(0.72 0.20 25),oklch(0.85 0.18 95));
  display:flex;align-items:center;justify-content:center;
  font-weight:700;font-size:12px;color:#07080b;font-family:var(--mono);
}
.nav-title{font-size:14px;font-weight:600;color:var(--ink-0);flex:1}
.btn{
  border:1px solid var(--ink-4);background:var(--bg-2);color:var(--ink-1);
  padding:6px 14px;border-radius:7px;cursor:pointer;font-size:12px;font-weight:500;
  font-family:var(--font);transition:background .15s;text-decoration:none;
  display:inline-flex;align-items:center;gap:6px;
}
.btn:hover{background:var(--bg-3);border-color:var(--ink-2);text-decoration:none}
.btn.primary{background:var(--accent);color:var(--bg-0);border-color:var(--accent);font-weight:600}
.btn.primary:hover{background:oklch(0.9 0.18 95)}
.wrap{max-width:900px;margin:0 auto;padding:40px 28px 80px}
h1{font-family:var(--serif);font-style:italic;font-size:36px;font-weight:400;color:var(--ink-0);letter-spacing:-.02em;margin-bottom:10px}
h2{font-size:17px;font-weight:600;color:var(--ink-0);margin:0 0 14px}
h3{font-size:14px;font-weight:600;color:var(--ink-0);margin:0 0 10px}
p{margin-bottom:12px;color:var(--ink-2)}
code{font-family:var(--mono);font-size:12px;background:var(--bg-2);padding:2px 6px;border-radius:4px;color:var(--accent)}
pre{font-family:var(--mono);font-size:12px;background:var(--bg-2);border:1px solid var(--ink-4);border-radius:8px;padding:14px 16px;overflow-x:auto;margin:10px 0;color:var(--ink-1)}
.sec-h{
  font-family:var(--mono);font-size:11px;letter-spacing:.14em;text-transform:uppercase;
  color:var(--ink-3);font-weight:600;margin:36px 0 16px;
  display:flex;align-items:center;gap:12px;
}
.sec-h::after{content:"";flex:1;height:1px;background:var(--ink-4)}
.card{background:var(--bg-1);border:1px solid var(--ink-4);border-radius:12px;padding:22px 24px;margin-bottom:14px}
.card.ok{border-color:oklch(0.78 0.16 155 / .5);background:oklch(0.78 0.16 155 / .06)}
.card.warn{border-color:oklch(0.82 0.14 70 / .5);background:oklch(0.82 0.14 70 / .06)}
.card.info{border-color:oklch(0.72 0.18 240 / .5);background:oklch(0.72 0.18 240 / .06)}
.status-row{display:flex;align-items:center;gap:12px;font-size:14px}
.dot{width:10px;height:10px;border-radius:50%;flex-shrink:0;background:var(--ink-4)}
.dot.green{background:oklch(0.78 0.16 155)}
.dot.yellow{background:oklch(0.82 0.14 70);animation:pulse 1.5s infinite}
.dot.red{background:oklch(0.72 0.20 25)}
@keyframes pulse{0%,100%{opacity:1}50%{opacity:.4}}
.qr-box{display:flex;gap:32px;align-items:flex-start;flex-wrap:wrap;margin:16px 0}
.qr-code{background:#f6f7fa;border-radius:12px;padding:12px;flex-shrink:0}
.qr-info{flex:1;min-width:200px}
.step-list{list-style:none;padding:0;margin:0;counter-reset:steps}
.step-list li{counter-increment:steps;padding:10px 0 10px 44px;position:relative;border-bottom:1px solid var(--bg-3)}
.step-list li:last-child{border-bottom:none}
.step-list li::before{content:counter(steps);position:absolute;left:0;top:10px;width:28px;height:28px;border-radius:50%;background:var(--bg-2);border:1px solid var(--ink-4);display:flex;align-items:center;justify-content:center;font-family:var(--mono);font-size:11px;font-weight:600;color:var(--accent)}
.tabs{display:flex;gap:4px;margin-bottom:16px;background:var(--bg-2);border-radius:8px;padding:4px;border:1px solid var(--ink-4)}
.tab-btn{flex:1;padding:8px;background:none;border:none;color:var(--ink-2);font-size:12px;font-weight:500;font-family:var(--font);border-radius:6px;cursor:pointer;transition:background .15s,color .15s}
.tab-btn.active{background:var(--bg-0);color:var(--ink-0);box-shadow:0 1px 4px rgba(0,0,0,.3)}
.tab-panel{display:none}
.tab-panel.active{display:block}
.badge{display:inline-block;font-family:var(--mono);font-size:10px;font-weight:600;padding:2px 8px;border-radius:4px;margin-left:6px}
.badge.free{background:oklch(0.78 0.16 155 / .2);color:oklch(0.85 0.14 155);border:1px solid oklch(0.78 0.16 155 / .4)}
.badge.recommended{background:var(--accent);color:var(--bg-0)}
.tip{background:var(--bg-2);border-left:3px solid var(--accent);border-radius:4px;padding:10px 14px;font-size:13px;margin:10px 0;color:var(--ink-1)}
.copy-btn{
  float:right;margin-top:-4px;
  background:var(--bg-3);border:1px solid var(--ink-4);color:var(--ink-2);
  padding:3px 10px;border-radius:5px;font-size:11px;font-family:var(--mono);cursor:pointer;
  transition:background .12s
}
.copy-btn:hover{background:var(--bg-0);color:var(--ink-0)}
.grid2{display:grid;grid-template-columns:1fr 1fr;gap:14px;margin:16px 0}
@media(max-width:680px){.grid2{grid-template-columns:1fr}.wrap{padding:20px 14px 60px}.nav{padding:0 14px}.qr-box{flex-direction:column}}
</style>
</head>
<body>

<nav class="nav">
  <div class="mark">M</div>
  <div class="nav-title">Mehad QA &mdash; OTP Setup</div>
  <a class="btn" href="index.html">&#8592; Back</a>
</nav>

<div class="wrap">

<div style="margin-bottom:28px">
  <h1>Phone OTP Setup</h1>
  <p style="font-size:15px;color:var(--ink-1)">
    Mehad sends one-time passwords via <strong style="color:var(--ink-0)">WhatsApp</strong> (not SMS).
    This page helps you connect a phone number so the test suite can read OTPs automatically &mdash;
    no manual copy-paste needed.
  </p>
</div>

<!-- ─── Live WAHA status ──────────────────────────────────────────────── -->
<div class="sec-h">Live Status</div>

<div id="waha-status-card" class="card info">
  <div class="status-row">
    <div class="dot yellow" id="waha-dot"></div>
    <span id="waha-status-text">Checking WAHA at localhost:3000&hellip;</span>
  </div>
  <p id="waha-status-detail" style="margin:8px 0 0;font-size:12px;color:var(--ink-3)">
    WAHA is a free open-source WhatsApp API that runs on your computer.
  </p>
</div>

<!-- ─── Test phone QR ─────────────────────────────────────────────────── -->
<div class="sec-h">Test Phone QR Code</div>

<div class="card">
  <h2>Scan to open the test number on WhatsApp</h2>
  <div class="qr-box">
    <div class="qr-code" id="wa-qrcode"></div>
    <div class="qr-info">
      <h3>Test phone number</h3>
      <p>
        Scan this QR code with any WhatsApp-connected phone to open a chat with the
        test account. You can then use this number to receive OTPs during production testing.
      </p>
      <p><strong style="color:var(--ink-0)">Default test number:</strong> <code>+880 98976564</code></p>
      <p style="font-size:12px;color:var(--ink-3)">
        This is the staging pre-registered number. For production, set your own number
        via the <code>PROD_TEST_PHONE</code> environment variable.
      </p>
      <a class="btn" href="https://wa.me/88098976564" target="_blank" rel="noopener" style="margin-top:8px;display:inline-flex">
        &#128172; Open in WhatsApp
      </a>
    </div>
  </div>
</div>

<!-- WAHA QR (only shown when WAHA is running locally) -->
<div id="waha-qr-section" style="display:none">
  <div class="card ok">
    <h2>Scan to connect WAHA ✅</h2>
    <div class="qr-box">
      <div class="qr-code" id="waha-qr-img"></div>
      <div class="qr-info">
        <h3>Connect your WhatsApp to WAHA</h3>
        <p>Open WhatsApp on your phone &rarr; Settings &rarr; Linked Devices &rarr; Link a Device &rarr; scan this QR code.</p>
        <p style="font-size:12px;color:var(--ink-3)">Session is saved automatically. You only need to scan once.</p>
        <a class="btn primary" href="http://localhost:3000/dashboard" target="_blank" rel="noopener">
          Open WAHA Dashboard ↗
        </a>
      </div>
    </div>
  </div>
</div>

<!-- ─── Setup Guide ───────────────────────────────────────────────────── -->
<div class="sec-h">Setup Guide</div>

<div class="tabs">
  <button class="tab-btn active" onclick="showTab('waha')">🐳 WAHA Docker <span class="badge recommended">recommended</span></button>
  <button class="tab-btn" onclick="showTab('wajs')">🟢 Node.js bridge</button>
  <button class="tab-btn" onclick="showTab('sms')">📩 Free SMS receivers</button>
</div>

<!-- Tab A: WAHA -->
<div class="tab-panel active" id="tab-waha">
  <div class="card">
    <h2>Option A &mdash; WAHA Docker <span class="badge free">FREE</span> <span class="badge recommended">works for any country</span></h2>
    <p>WAHA is a free open-source WhatsApp HTTP API. It runs on your computer in Docker and lets the test suite read OTPs automatically.</p>

    <h3>Step 1 &mdash; Install Docker Desktop</h3>
    <ul class="step-list">
      <li>Go to <a href="https://www.docker.com/products/docker-desktop/" target="_blank" rel="noopener">docker.com/products/docker-desktop</a> and download Docker Desktop for your operating system (Windows / Mac / Linux).</li>
      <li>Install it and open the Docker Desktop app. Wait until you see <strong style="color:var(--ink-0)">Docker is running</strong> in the system tray / menu bar.</li>
      <li>Verify in a terminal: <code>docker --version</code> (should print a version number)</li>
    </ul>

    <h3 style="margin-top:18px">Step 2 &mdash; Start WAHA</h3>
    <div class="tip">Copy and paste this single command into your terminal:</div>
    <pre><button class="copy-btn" onclick="copyText(this,'docker run -d --name waha -p 3000:3000 devlikeapro/waha')">copy</button>docker run -d --name waha -p 3000:3000 devlikeapro/waha</pre>
    <p style="font-size:12px">
      <code>-d</code> = runs in background &nbsp;·&nbsp;
      <code>--name waha</code> = gives it a name &nbsp;·&nbsp;
      <code>-p 3000:3000</code> = opens port 3000 &nbsp;·&nbsp;
      <code>devlikeapro/waha</code> = the free WAHA image
    </p>

    <h3 style="margin-top:18px">Step 3 &mdash; Scan the QR code</h3>
    <ul class="step-list">
      <li>Open <a href="http://localhost:3000/dashboard" target="_blank" rel="noopener">http://localhost:3000/dashboard</a> in your browser.</li>
      <li>Click <strong style="color:var(--ink-0)">Start session</strong> if there is no active session.</li>
      <li>A QR code will appear. Open WhatsApp on your test phone &rarr; <strong>Settings &rarr; Linked Devices &rarr; Link a Device</strong> &rarr; scan the QR code.</li>
      <li>Once connected you will see <strong style="color:oklch(0.78 0.16 155)">Session WORKING</strong>. You only need to do this once &mdash; the session is saved automatically.</li>
    </ul>

    <h3 style="margin-top:18px">Step 4 &mdash; Configure your <code>.env</code></h3>
    <pre><button class="copy-btn" onclick="copyText(this,'PROD_OTP_BACKEND=waha\nWAHA_URL=http://localhost:3000\nWAHA_SESSION=default\nWAHA_CHAT_ID=+88098976564@c.us\nPROD_COUNTRY_CODE=+880\nPROD_TEST_PHONE=98976564')">copy</button>PROD_OTP_BACKEND=waha
WAHA_URL=http://localhost:3000
WAHA_SESSION=default
WAHA_CHAT_ID=+88098976564@c.us   # replace with your test number
PROD_COUNTRY_CODE=+880
PROD_TEST_PHONE=98976564</pre>
    <p style="font-size:12px;color:var(--ink-3)">The chat ID format is <code>+{country_code}{local_number}@c.us</code>. For Bangladesh: <code>+88098976564@c.us</code></p>

    <h3 style="margin-top:18px">Management commands</h3>
    <div class="grid2">
      <div>
        <p style="font-family:var(--mono);font-size:11px;color:var(--ink-3);margin-bottom:4px">Stop WAHA</p>
        <pre style="margin:0">docker stop waha</pre>
      </div>
      <div>
        <p style="font-family:var(--mono);font-size:11px;color:var(--ink-3);margin-bottom:4px">Start again</p>
        <pre style="margin:0">docker start waha</pre>
      </div>
      <div>
        <p style="font-family:var(--mono);font-size:11px;color:var(--ink-3);margin-bottom:4px">View logs</p>
        <pre style="margin:0">docker logs waha -f</pre>
      </div>
      <div>
        <p style="font-family:var(--mono);font-size:11px;color:var(--ink-3);margin-bottom:4px">Remove &amp; restart fresh</p>
        <pre style="margin:0">docker rm -f waha &amp;&amp; docker run ...</pre>
      </div>
    </div>
  </div>
</div>

<!-- Tab B: Node.js bridge -->
<div class="tab-panel" id="tab-wajs">
  <div class="card">
    <h2>Option B &mdash; whatsapp-web.js Node.js bridge <span class="badge free">FREE</span></h2>
    <p>An open-source Node.js library that connects WhatsApp via QR scan and runs a local HTTP server the test suite can query for OTPs.</p>

    <ul class="step-list">
      <li>Install Node.js 18+ from <a href="https://nodejs.org" target="_blank" rel="noopener">nodejs.org</a> if you don't have it. Verify: <code>node --version</code></li>
      <li>Open a terminal in this project's <code>scripts/</code> folder:
        <pre><button class="copy-btn" onclick="copyText(this,'cd scripts\nnpm install')">copy</button>cd scripts
npm install</pre>
      </li>
      <li>Start the bridge:
        <pre><button class="copy-btn" onclick="copyText(this,'node whatsapp_otp_server.js')">copy</button>node whatsapp_otp_server.js</pre>
        A QR code appears in the terminal. Scan it with WhatsApp (Settings &rarr; Linked Devices &rarr; Link a Device).
      </li>
      <li>Once you see <strong style="color:oklch(0.78 0.16 155)">WhatsApp client ready</strong>, the bridge is running at <code>http://localhost:3001/otp</code>.</li>
      <li>Set in <code>.env</code>:
        <pre><button class="copy-btn" onclick="copyText(this,'PROD_OTP_BACKEND=whatsapp_local\nWA_OTP_PORT=3001')">copy</button>PROD_OTP_BACKEND=whatsapp_local
WA_OTP_PORT=3001</pre>
      </li>
    </ul>
    <div class="tip">&#128274; The session is saved to <code>scripts/.wwebjs_auth/</code>. You won't need to scan the QR again unless you log out or delete that folder.</div>
  </div>
</div>

<!-- Tab C: SMS receivers -->
<div class="tab-panel" id="tab-sms">
  <div class="card">
    <h2>Option C &mdash; Free public SMS receivers <span class="badge free">FREE</span></h2>
    <div class="card warn" style="margin-bottom:16px">
      <strong style="color:oklch(0.82 0.14 70)">⚠️ WhatsApp only</strong><br/>
      Mehad sends OTPs via WhatsApp, not SMS. SMS receivers <strong>will not work</strong> for Mehad
      production tests. Use Options A or B instead. SMS receivers are listed here for testing
      with other apps that use real SMS.
    </div>

    <div class="grid2">
      <div class="card" style="margin:0">
        <h3>receivesmsfast.com</h3>
        <p style="font-size:12px">Bangladesh numbers. Free, no account.</p>
        <pre style="font-size:11px">PROD_OTP_BACKEND=receivesmsfast
RECEIVESMSFAST_NUMBER=8801755572498</pre>
      </div>
      <div class="card" style="margin:0">
        <h3>quackr.io</h3>
        <p style="font-size:12px">US/EU numbers. Free, no account.</p>
        <pre style="font-size:11px">PROD_OTP_BACKEND=quackr
QUACKR_NUMBER=12025551234</pre>
      </div>
      <div class="card" style="margin:0">
        <h3>sms-online.co</h3>
        <p style="font-size:12px">Many countries. Free, no account.</p>
        <pre style="font-size:11px">PROD_OTP_BACKEND=smsonline
SMSONLINE_NUMBER=12025551234</pre>
      </div>
      <div class="card" style="margin:0">
        <h3>Staging (no OTP needed)</h3>
        <p style="font-size:12px">dev.mehadedu.com always returns <code>123456</code>.</p>
        <pre style="font-size:11px">TEST_OTP=123456
TEST_PHONE=98976564</pre>
      </div>
    </div>
  </div>
</div>

<!-- ─── CI/CD Guide ───────────────────────────────────────────────────── -->
<div class="sec-h">CI/CD (GitHub Actions)</div>

<div class="card">
  <h2>How WAHA works in GitHub Actions</h2>
  <p>
    The CI workflow automatically starts a WAHA Docker container for the main test jobs.
    Docker is already installed on GitHub Actions Ubuntu runners &mdash; no extra setup needed.
  </p>

  <h3>How CI picks the OTP backend</h3>
  <ul class="step-list">
    <li><strong>Staging tests (default)</strong> &mdash; <code>BASE_URL=dev.mehadedu.com</code> &rarr; fixed OTP <code>123456</code> is used. WAHA starts but isn't needed.</li>
    <li><strong>Production tests</strong> &mdash; Set <code>BASE_URL=https://mehadedu.com/en</code> in the workflow dispatch. Also set <code>PROD_OTP_BACKEND=waha</code> and configure the secrets below.</li>
  </ul>

  <h3 style="margin-top:18px">GitHub Secrets to configure</h3>
  <p>Go to your repository &rarr; <strong>Settings &rarr; Secrets and variables &rarr; Actions &rarr; New repository secret</strong>.</p>
  <div style="overflow-x:auto">
  <table style="width:100%;border-collapse:collapse;font-size:12px;margin-top:10px">
    <thead>
      <tr style="background:var(--bg-2)">
        <th style="text-align:left;padding:8px 12px;border:1px solid var(--ink-4);font-family:var(--mono)">Secret name</th>
        <th style="text-align:left;padding:8px 12px;border:1px solid var(--ink-4)">Example value</th>
        <th style="text-align:left;padding:8px 12px;border:1px solid var(--ink-4)">Description</th>
      </tr>
    </thead>
    <tbody>
      <tr><td style="padding:8px 12px;border:1px solid var(--ink-4);font-family:var(--mono)">PROD_OTP_BACKEND</td><td style="padding:8px 12px;border:1px solid var(--ink-4)"><code>waha</code></td><td style="padding:8px 12px;border:1px solid var(--ink-4)">Which OTP system to use</td></tr>
      <tr><td style="padding:8px 12px;border:1px solid var(--ink-4);font-family:var(--mono)">WAHA_CHAT_ID</td><td style="padding:8px 12px;border:1px solid var(--ink-4)"><code>+88098976564@c.us</code></td><td style="padding:8px 12px;border:1px solid var(--ink-4)">WhatsApp chat ID of the test phone</td></tr>
      <tr><td style="padding:8px 12px;border:1px solid var(--ink-4);font-family:var(--mono)">WAHA_SESSION</td><td style="padding:8px 12px;border:1px solid var(--ink-4)"><code>default</code></td><td style="padding:8px 12px;border:1px solid var(--ink-4)">WAHA session name (leave as default)</td></tr>
      <tr><td style="padding:8px 12px;border:1px solid var(--ink-4);font-family:var(--mono)">PROD_TEST_PHONE</td><td style="padding:8px 12px;border:1px solid var(--ink-4)"><code>98976564</code></td><td style="padding:8px 12px;border:1px solid var(--ink-4)">Local part of the production test number</td></tr>
      <tr><td style="padding:8px 12px;border:1px solid var(--ink-4);font-family:var(--mono)">PROD_COUNTRY_CODE</td><td style="padding:8px 12px;border:1px solid var(--ink-4)"><code>+880</code></td><td style="padding:8px 12px;border:1px solid var(--ink-4)">Country code for production number</td></tr>
    </tbody>
  </table>
  </div>

  <h3 style="margin-top:18px">Important: WAHA session in CI</h3>
  <div class="tip">
    &#128274; Each CI run starts a <em>fresh</em> WAHA container with no WhatsApp session.
    For production OTP in CI, you have two options:<br/><br/>
    <strong style="color:var(--ink-0)">Option 1 (recommended)</strong> &mdash; Self-host a permanent WAHA instance, set
    <code>WAHA_URL</code> secret to your server URL (e.g. <code>https://waha.yourserver.com</code>).
    The CI job will use your always-on session.<br/><br/>
    <strong style="color:var(--ink-0)">Option 2</strong> &mdash; Keep testing against <code>dev.mehadedu.com</code> staging
    (no real OTP needed &mdash; always uses <code>123456</code>).
  </div>
</div>

<!-- ─── Quick reference ───────────────────────────────────────────────── -->
<div class="sec-h">Quick Reference</div>

<div class="card">
  <h2>Which option should I choose?</h2>
  <div style="overflow-x:auto">
  <table style="width:100%;border-collapse:collapse;font-size:12px;margin-top:4px">
    <thead>
      <tr style="background:var(--bg-2)">
        <th style="text-align:left;padding:8px 12px;border:1px solid var(--ink-4)">Situation</th>
        <th style="text-align:left;padding:8px 12px;border:1px solid var(--ink-4)">Best option</th>
        <th style="text-align:left;padding:8px 12px;border:1px solid var(--ink-4)">Why</th>
      </tr>
    </thead>
    <tbody>
      <tr><td style="padding:8px 12px;border:1px solid var(--ink-4)">Testing on staging (<code>dev.mehadedu.com</code>)</td><td style="padding:8px 12px;border:1px solid var(--ink-4)">No setup needed</td><td style="padding:8px 12px;border:1px solid var(--ink-4)">Fixed OTP <code>123456</code> always works</td></tr>
      <tr><td style="padding:8px 12px;border:1px solid var(--ink-4)">Testing on production &mdash; have Docker</td><td style="padding:8px 12px;border:1px solid var(--ink-4)">WAHA Docker (Option A)</td><td style="padding:8px 12px;border:1px solid var(--ink-4)">One-time QR scan, works for any country</td></tr>
      <tr><td style="padding:8px 12px;border:1px solid var(--ink-4)">Testing on production &mdash; no Docker</td><td style="padding:8px 12px;border:1px solid var(--ink-4)">Node.js bridge (Option B)</td><td style="padding:8px 12px;border:1px solid var(--ink-4)">Only needs Node.js 18+</td></tr>
      <tr><td style="padding:8px 12px;border:1px solid var(--ink-4)">CI/CD with production OTP</td><td style="padding:8px 12px;border:1px solid var(--ink-4)">Self-hosted WAHA + <code>WAHA_URL</code> secret</td><td style="padding:8px 12px;border:1px solid var(--ink-4)">Persistent session, no QR rescan needed</td></tr>
      <tr><td style="padding:8px 12px;border:1px solid var(--ink-4)">Testing SMS (non-Mehad apps)</td><td style="padding:8px 12px;border:1px solid var(--ink-4)">receivesmsfast / quackr (Option C)</td><td style="padding:8px 12px;border:1px solid var(--ink-4)">Free public numbers, no setup</td></tr>
    </tbody>
  </table>
  </div>
</div>

<!-- ─── Footer ────────────────────────────────────────────────────────── -->
<footer style="margin-top:56px;padding-top:28px;border-top:1px solid var(--ink-4);text-align:center;color:var(--ink-3);font-size:12px">
  <div style="margin-bottom:8px">Built by <a href="https://www.linkedin.com/in/mejbaur/" target="_blank" rel="noopener" style="color:var(--ink-2)">Mejbaur Bahar Fagun</a> &mdash; Senior Software Engineer QA (IV) &middot; Markopolo.ai</div>
  <div><a href="index.html" style="color:var(--accent)">&larr; Back to dashboard</a></div>
</footer>

</div><!-- /wrap -->

<script>
// ── Tab switching ──────────────────────────────────────────────────────
function showTab(name) {
  document.querySelectorAll('.tab-btn').forEach(function(b){ b.classList.remove('active'); });
  document.querySelectorAll('.tab-panel').forEach(function(p){ p.classList.remove('active'); });
  document.querySelector('[onclick="showTab(\''+name+'\')"]').classList.add('active');
  document.getElementById('tab-'+name).classList.add('active');
}

// ── Copy to clipboard ─────────────────────────────────────────────────
function copyText(btn, text) {
  navigator.clipboard.writeText(text).then(function(){
    var orig = btn.textContent; btn.textContent = 'copied!';
    setTimeout(function(){ btn.textContent = orig; }, 1500);
  });
}

// ── Generate test-phone WhatsApp QR code ─────────────────────────────
var testPhone = '+88098976564';
new QRCode(document.getElementById('wa-qrcode'), {
  text: 'https://wa.me/88098976564',
  width: 180, height: 180,
  colorDark: '#07080b', colorLight: '#f6f7fa',
  correctLevel: QRCode.CorrectLevel.M
});

// ── Live WAHA status check ────────────────────────────────────────────
(function checkWaha() {
  var dot = document.getElementById('waha-dot');
  var txt = document.getElementById('waha-status-text');
  var det = document.getElementById('waha-status-detail');
  var qrSec = document.getElementById('waha-qr-section');
  var card = document.getElementById('waha-status-card');

  fetch('http://localhost:3000/api/version', { mode: 'cors', signal: AbortSignal.timeout(3000) })
    .then(function(r){ return r.json(); })
    .then(function(v){
      // WAHA is running — check session status
      return fetch('http://localhost:3000/api/sessions', { mode: 'cors', signal: AbortSignal.timeout(3000) });
    })
    .then(function(r){ return r.json(); })
    .then(function(sessions){
      var sess = sessions && sessions[0];
      var status = sess ? sess.status : 'UNKNOWN';
      if (status === 'WORKING') {
        dot.className = 'dot green';
        txt.textContent = 'WAHA is running and connected ✅';
        det.textContent = 'WhatsApp session active. OTPs will be captured automatically.';
        card.className = 'card ok';
        qrSec.style.display = 'none';
      } else if (status === 'SCAN_QR_CODE') {
        dot.className = 'dot yellow';
        txt.textContent = 'WAHA is running — scan the QR code to connect ↓';
        det.textContent = 'Open WhatsApp → Settings → Linked Devices → Link a Device → scan the QR below.';
        card.className = 'card warn';
        // Load WAHA QR image
        var img = document.createElement('img');
        img.src = 'http://localhost:3000/api/sessions/default/auth/qr?format=image&' + Date.now();
        img.style.cssText = 'width:180px;height:180px;border-radius:8px';
        img.onerror = function(){ img.alt = 'Could not load QR — open http://localhost:3000/dashboard'; };
        document.getElementById('waha-qr-img').appendChild(img);
        qrSec.style.display = 'block';
      } else {
        dot.className = 'dot yellow';
        txt.textContent = 'WAHA is running (status: ' + status + ')';
        det.textContent = 'Open http://localhost:3000/dashboard to check the session.';
        card.className = 'card warn';
      }
    })
    .catch(function(){
      dot.className = 'dot red';
      txt.textContent = 'WAHA is not running locally';
      det.innerHTML = 'Start WAHA with: <code>docker run -d --name waha -p 3000:3000 devlikeapro/waha</code> &mdash; then reload this page.';
      card.className = 'card';
    });
})();
</script>
</body>
</html>"""


def _archive_dir() -> Path:
    """Per-run archive folder where this run's individual reports go."""
    arc = SITE_DIR / "history" / f"run-{RUN_NUMBER}"
    arc.mkdir(parents=True, exist_ok=True)
    return arc


def _inject_data_flow_banner(report_html: "Path") -> None:
    """Inject a sticky Data Flow link banner at the top of report.html."""
    if not report_html.exists():
        return
    banner = (
        '<div style="position:sticky;top:0;z-index:9999;background:#1d4ed8;'
        'color:#fff;text-align:center;padding:10px 16px;font-size:14px;'
        'font-weight:600;letter-spacing:.03em">'
        '📡 <a href="data-flow.html" style="color:#bfdbfe;text-decoration:underline">'
        'View Real-Time Data Flow Report</a>'
        ' &nbsp;·&nbsp; '
        '<a href="data-flow.html" style="color:#fff;background:#1e40af;'
        'padding:4px 14px;border-radius:6px;text-decoration:none">'
        'Open Data Flow →</a>'
        '</div>'
    )
    html = report_html.read_text(encoding="utf-8")
    if "data-flow.html" in html:
        return  # already injected
    # Insert banner as first element INSIDE <body>
    injected = re.sub(r'(<body[^>]*>)', r'\1' + banner.replace('\\', '\\\\'), html, count=1)
    if "data-flow.html" not in injected:
        # fallback: append banner before first <div / <nav
        for tag in ("<div", "<nav", "<header", "<main"):
            if tag in html:
                injected = html.replace(tag, banner + tag, 1)
                break
    report_html.write_text(injected, encoding="utf-8")
    print("  ✅ Data Flow banner injected into report.html")


def _find_json_report(reports_dir: "Path", filename: str) -> "Path | None":
    """Find a JSON report by trying direct path first, then recursive search.
    Handles CI artifact download path duplication (reports/ → reports/reports/)."""
    direct = reports_dir / filename
    if direct.exists():
        return direct
    for hit in reports_dir.rglob(filename):
        if hit.is_file():
            return hit
    return None


def _build_data_flow_page(reports_dir: "Path", site_dir: "Path") -> None:
    """Generate gh-pages-site/data-flow.html from realtime + DF JSON reports."""
    rt_json  = _find_json_report(reports_dir, "realtime_flow_report.json")
    df_json  = _find_json_report(reports_dir, "data_flow_report.json")

    rt_data: dict = {}
    df_rows: list = []

    if rt_json:
        try:
            rt_data = json.loads(rt_json.read_text(encoding="utf-8"))
        except Exception:
            pass
    if df_json:
        try:
            raw = json.loads(df_json.read_text(encoding="utf-8"))
            df_rows = raw if isinstance(raw, list) else []
        except Exception:
            pass

    booking      = rt_data.get("booking", {})
    created_data = rt_data.get("created_data", {})
    rt_steps  = rt_data.get("steps", [])
    all_steps = rt_steps + df_rows

    bid     = booking.get("booking_id")    or ""
    amount  = booking.get("payment_amount") or ""
    tutor   = booking.get("tutor_name")    or ""
    booked  = booking.get("booked_at")     or ""

    # Created data (from Phase 1 of test_e2e_create_book_verify.py)
    slot_data   = created_data.get("slot",   {})
    course_data = created_data.get("course", {})
    # Also try loading from setup_data_summary.json if not in realtime_flow_report
    if not slot_data and not course_data:
        setup_json2 = _find_json_report(reports_dir, "setup_data_summary.json")
        if setup_json2:
            try:
                setup2 = json.loads(setup_json2.read_text(encoding="utf-8"))
                avail = setup2.get("availability_slots", [])
                if avail:
                    s0 = avail[0]
                    slot_data = {
                        "date":       s0.get("date", ""),
                        "day":        s0.get("day", ""),
                        "start_time": s0.get("start_time", ""),
                        "end_time":   s0.get("end_time", ""),
                        "created":    s0.get("status") == "created",
                    }
                gs2 = setup2.get("group_session", {})
                if gs2:
                    course_data = {
                        "name":       gs2.get("name", ""),
                        "price_sar":  gs2.get("price_sar", ""),
                        "date":       gs2.get("date", ""),
                        "start_time": gs2.get("start_time", ""),
                        "end_time":   gs2.get("end_time", ""),
                        "created":    gs2.get("created", False),
                    }
            except Exception:
                pass

    # Fallback 1: setup_data_summary.json (setup_test_data.py output)
    if not bid:
        setup_json = _find_json_report(reports_dir, "setup_data_summary.json")
        if setup_json:
            try:
                setup = json.loads(setup_json.read_text(encoding="utf-8"))
                sb = setup.get("student_booking", {})
                bid    = sb.get("booking_id",  "") or bid
                tutor  = sb.get("tutor_name",  "") or tutor
                amount = sb.get("price_sar",   "") or amount
                booked = sb.get("date",        "") or booked
            except Exception:
                pass

    # Fallback 2: setup_booking_id.txt plain-text file
    if not bid:
        txt_file = _find_json_report(reports_dir, "setup_booking_id.txt")
        if txt_file:
            try:
                bid = txt_file.read_text(encoding="utf-8").strip() or bid
            except Exception:
                pass

    # Fallback 3: scan ALL step data in all_steps for any booking_id field
    if not bid:
        for s in all_steps:
            cand = s.get("booking_id") or s.get("bid") or ""
            if cand and cand != "—":
                bid = cand
                break

    # Fallback 4: last-resort regex scan across all downloaded JSON reports
    if not bid:
        import re as _re
        _bid_re = _re.compile(r"[D]?BK-\d{8}-[A-Z0-9]{4,8}")
        for _jf in sorted(reports_dir.rglob("*.json")):
            try:
                _hits = _bid_re.findall(_jf.read_text(encoding="utf-8", errors="ignore"))
                if _hits:
                    bid = _hits[0]
                    break
            except Exception:
                pass

    bid    = bid    or "—"
    amount = amount or "—"
    tutor  = tutor  or "—"
    booked = booked or "—"

    total  = len(all_steps)
    passed = sum(1 for s in all_steps if s.get("status") == "PASS")
    failed = sum(1 for s in all_steps if s.get("status") == "FAIL")
    xfail  = sum(1 for s in all_steps if s.get("status") in ("XFAIL", "SKIP"))
    rate   = int(passed / max(total, 1) * 100)

    def badge(s: str) -> str:
        c = {"PASS": "#16a34a", "FAIL": "#dc2626",
             "SKIP": "#d97706", "XFAIL": "#7c3aed"}.get(s, "#6b7280")
        return (f'<span style="background:{c};color:#fff;padding:2px 8px;'
                f'border-radius:4px;font-size:11px;font-weight:700">{s}</span>')

    # Module verification table
    modules = [
        ("DF-01", "Student Wallet / Payments",     "Real transactions with tutor name + SAR amount"),
        ("DF-02", "Student My Bookings",           "Upcoming + Session History tabs. Cards have schedule."),
        ("DF-03", "Session Recordings",            "View Recording only on completed sessions (not upcoming)"),
        ("DF-04", "Super Admin Sessions",          "Page accessible. No mock data. Status filter works."),
        ("DF-05", "Tutor Calendar",                "Calendar widget loads. Slot indicators visible."),
        ("DF-06", "Tutor Booked Sessions",         "All Sessions heading. Upcoming + History tabs. Search input."),
        ("DF-07", "Course / Group Sessions",       "Real heading. No mock data. Visible in student profile."),
        ("DF-08", "Tutor Earnings & Payouts",      "Available Balance, Pending, Total Earnings sections."),
        ("RT-01", "Real Booking Created",          f"Booking ID: {bid} · Amount: {amount} SAR"),
        ("RT-02", "Student My Bookings (live)",    "Page OK after booking. State: pending-payment → appears on confirmation."),
        ("RT-03", "Student Wallet (live)",         "Recent Transactions section present. SAR amounts real."),
        ("RT-04", "Tutor Booked Sessions (live)",  "Page structure correct. Upcoming sessions content present."),
        ("RT-05", "Tutor Calendar (live)",         "Loads post-booking. Slot elements visible."),
        ("RT-06", "Tutor Earnings (live)",         "Earnings page loads. Balance/Pending/Payout sections present."),
        ("CC",    "Cross-Module Consistency",      "All 5 dashboards load clean. No 500/404."),
    ]
    mod_rows = ""
    for mid, name, finding in modules:
        step_match = next(
            (s for s in all_steps
             if s.get("step", "").startswith(mid)
             or s.get("requirement", "").startswith(mid)
             or mid in s.get("module", "")),
            None
        )
        st = step_match.get("status") if step_match else None
        if st == "PASS":
            icon, bg = "✅", "#f0fdf4"
        elif st in ("SKIP", "XFAIL") or st is None:
            icon, bg = "⏭", "#fefce8"   # yellow = skipped/no data
        else:
            icon, bg = "❌", "#fee2e2"
        mod_rows += (
            f'<tr style="background:{bg}">'
            f'<td style="font-weight:700;font-size:13px">{icon} {mid}</td>'
            f'<td style="font-weight:600;font-size:13px">{name}</td>'
            f'<td style="font-size:13px">{finding}</td></tr>'
        )

    # Step log rows
    step_rows = ""
    prev_step = ""
    for s in all_steps:
        step = s.get("step") or s.get("requirement", "")
        sc = f'<td style="font-weight:700;white-space:nowrap">{step}</td>' if step != prev_step else "<td></td>"
        prev_step = step
        _mod = (s.get('module')
                or (f"{s.get('source_module','')} → {s.get('dest_module','')}"
                    if s.get('source_module') or s.get('dest_module') else ''))
        step_rows += (
            f"<tr>{sc}"
            f"<td style='font-size:12px;color:#374151'>{_mod}</td>"
            f"<td><code style='font-size:11px'>{str(s.get('data_used') or s.get('data',''))[:100]}</code></td>"
            f"<td><code style='font-size:11px;color:#2563eb'>{s.get('booking_id','') or '—'}</code></td>"
            f"<td>{badge(s.get('status',''))}</td>"
            f"<td style='font-size:11px;color:#475569'>{str(s.get('detail',''))[:120]}</td>"
            f"<td style='font-size:11px;color:#94a3b8'>{s.get('ts','')}</td></tr>"
        )

    if not step_rows:
        step_rows = ("<tr><td colspan='7' style='text-align:center;padding:28px;"
                     "color:#94a3b8'>No data yet — run tests/test_data_flow_e2e.py and "
                     "tests/test_realtime_data_flow.py to populate this report.</td></tr>")

    # ── "What automation created" section ────────────────────────────────────────
    def _field(k: str, v: str) -> str:
        return (f'<div class="field"><div class="k">{k}</div>'
                f'<div class="v" style="font-size:14px">{v or "—"}</div></div>')

    slot_ok   = slot_data.get("created", False)
    course_ok = course_data.get("created", False)
    slot_icon   = "✅" if slot_ok   else "⏳"
    course_icon = "✅" if course_ok else "⏳"

    slot_fields   = ""
    course_fields = ""
    if slot_data:
        slot_fields = (
            _field("Date",       slot_data.get("date", ""))
            + _field("Day",      slot_data.get("day", ""))
            + _field("Time",     f"{slot_data.get('start_time','')}–{slot_data.get('end_time','')}")
            + _field("Status",   "Created ✅" if slot_ok else "Attempted ⏳")
        )
    if course_data:
        course_fields = (
            _field("Name",       course_data.get("name", ""))
            + _field("Price",    f"{course_data.get('price_sar','')} SAR / student")
            + _field("Date",     course_data.get("date", ""))
            + _field("Time",     f"{course_data.get('start_time','')}–{course_data.get('end_time','')}")
            + _field("Status",   "Created ✅" if course_ok else "Attempted ⏳")
        )

    if slot_data or course_data:
        created_data_html = f"""
<div class="booking-card" style="border-color:#16a34a;margin-top:16px">
  <h3 style="color:#166534">📋 What Automation Created During This Run</h3>
  <div style="display:flex;gap:32px;flex-wrap:wrap">
    <div>
      <div style="font-size:12px;font-weight:700;color:#4b5563;text-transform:uppercase;
                  letter-spacing:.05em;margin-bottom:8px">{slot_icon} 1-to-1 Availability Slot</div>
      {slot_fields or "<span style='color:#94a3b8;font-size:13px'>Not created this run</span>"}
    </div>
    <div style="border-left:1px solid #e2e8f0;padding-left:32px">
      <div style="font-size:12px;font-weight:700;color:#4b5563;text-transform:uppercase;
                  letter-spacing:.05em;margin-bottom:8px">{course_icon} Group Session / Course</div>
      {course_fields or "<span style='color:#94a3b8;font-size:13px'>Not created this run</span>"}
    </div>
  </div>
</div>"""
    else:
        created_data_html = ""

    flow_items = [
        ("Student books slot", "→", f"Booking ID: {bid}", "Immediate"),
        ("Student pays (MyFatoorah)", "→", f"Transaction: {amount} SAR", "On payment success"),
        ("Bookings DB", "→", "Student My Bookings (Upcoming tab)", "Real-time on confirmation"),
        ("Bookings DB", "→", "Tutor Booked Sessions", "Real-time"),
        ("Bookings DB", "→", "Tutor Calendar (slot → booked)", "Real-time"),
        ("Payments DB", "→", "Student Wallet / Transactions", "On payment success"),
        ("Session completes", "→", "Tutor Earnings (pending → available)", "After completion"),
        ("Session completes", "→", "Recording in Student History", "After completion"),
        ("All actions", "→", "Super Admin Sessions", "Real-time"),
    ]
    flow_html = ""
    for src, verb, dest, timing in flow_items:
        flow_html += (
            f'<div style="display:flex;align-items:center;gap:10px;margin:7px 0;'
            f'font-size:13px;flex-wrap:wrap">'
            f'<span style="background:#eff6ff;color:#1d4ed8;padding:4px 12px;'
            f'border-radius:6px;font-weight:600;min-width:160px">{src}</span>'
            f'<span style="color:#94a3b8;font-weight:700">{verb}</span>'
            f'<span style="background:#f0fdf4;color:#166534;padding:4px 12px;'
            f'border-radius:6px;font-weight:600;min-width:180px">{dest}</span>'
            f'<span style="color:#94a3b8;font-size:11px">({timing})</span>'
            f'</div>'
        )

    html = f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Mehad — Data Flow Report · Run #{RUN_NUMBER}</title>
<style>
*{{box-sizing:border-box}}
body{{font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',sans-serif;margin:0;background:#f8fafc;color:#0f172a}}
.hero{{background:linear-gradient(135deg,#0f172a,#1e3a5f);color:#fff;padding:36px 48px}}
.hero h1{{margin:0 0 8px;font-size:28px;font-weight:800}}
.hero p{{margin:0;opacity:.7;font-size:14px}}
.kpi{{display:flex;gap:16px;padding:24px 48px;background:#fff;border-bottom:1px solid #e2e8f0;flex-wrap:wrap}}
.kpi-box{{border-radius:12px;padding:18px 28px;min-width:120px;text-align:center}}
.kpi-box .val{{font-size:36px;font-weight:900;line-height:1}}
.kpi-box .lbl{{font-size:11px;margin-top:5px;font-weight:700;text-transform:uppercase;letter-spacing:.06em;opacity:.7}}
.booking-card{{background:#fff;margin:24px 48px 0;border:2px solid #2563eb;border-radius:12px;padding:22px 30px}}
.booking-card h3{{margin:0 0 14px;font-size:15px;color:#1d4ed8;font-weight:700;text-transform:uppercase}}
.field{{display:inline-block;margin:0 24px 8px 0}}
.field .k{{color:#64748b;font-size:11px;text-transform:uppercase;font-weight:700}}
.field .v{{font-weight:800;font-size:16px;color:#0f172a;margin-top:2px}}
.card{{background:#fff;margin:20px 48px 0;border-radius:12px;padding:26px 30px;box-shadow:0 1px 6px rgba(0,0,0,.07)}}
.card h3{{margin:0 0 18px;font-size:16px;font-weight:700}}
table{{width:100%;border-collapse:collapse;background:#fff;border-radius:12px;overflow:hidden;box-shadow:0 1px 4px rgba(0,0,0,.07)}}
th{{background:#0f172a;color:#fff;padding:10px 14px;text-align:left;font-size:11px;text-transform:uppercase;letter-spacing:.06em}}
td{{padding:9px 14px;border-bottom:1px solid #f1f5f9;vertical-align:top}}
tr:hover td{{background:#f8fafc}}
.section{{padding:20px 48px 8px}}
footer{{text-align:center;padding:24px;font-size:12px;color:#94a3b8;border-top:1px solid #e2e8f0;margin-top:24px}}
</style>
</head>
<body>
<div class="hero">
  <h1>📡 Mehad — Real-Time Data Flow Report</h1>
  <p>Run #{RUN_NUMBER} &nbsp;·&nbsp; Target: https://dev.mehadedu.com/en &nbsp;·&nbsp; <a href="report.html" style="color:#93c5fd">← Back to QA Report</a></p>
</div>
<div class="kpi">
  <div class="kpi-box" style="background:#dcfce7"><div class="val" style="color:#16a34a">{passed}</div><div class="lbl">Passed</div></div>
  <div class="kpi-box" style="background:#fee2e2"><div class="val" style="color:#dc2626">{failed}</div><div class="lbl">Failed</div></div>
  <div class="kpi-box" style="background:#fef9c3"><div class="val" style="color:#d97706">{xfail}</div><div class="lbl">Expected</div></div>
  <div class="kpi-box" style="background:#eff6ff"><div class="val" style="color:#2563eb">{total}</div><div class="lbl">Total</div></div>
  <div class="kpi-box" style="background:#f0fdf4"><div class="val" style="color:#16a34a">{rate}%</div><div class="lbl">Pass Rate</div></div>
</div>
<div class="booking-card">
  <h3>🎯 Real Transaction — Created in This CI Run</h3>
  <div class="field"><div class="k">Booking ID</div><div class="v">{bid}</div></div>
  <div class="field"><div class="k">Amount</div><div class="v">{amount} SAR</div></div>
  <div class="field"><div class="k">Tutor</div><div class="v">{tutor}</div></div>
  <div class="field"><div class="k">Booked At</div><div class="v">{booked}</div></div>
  <div style="margin-top:10px;padding:10px;background:#eff6ff;border-radius:6px;font-size:13px;color:#1d4ed8;font-weight:600">
    ✅ This is a REAL booking from the live app — not mock data.
    The Booking ID, amount, and tutor name are all from the actual database.
  </div>
</div>
{created_data_html}
<div class="card">
  <h3>📡 Real-Time Data Flow Map</h3>
  {flow_html}
</div>
<div class="section">
  <h2 style="font-size:18px;font-weight:700;margin:0 0 14px">Module-by-Module Verification</h2>
  <table>
    <thead><tr><th>ID</th><th>Module</th><th>Verified Finding</th></tr></thead>
    <tbody>{mod_rows}</tbody>
  </table>
</div>
<div class="section" style="margin-top:20px;padding-bottom:28px">
  <h2 style="font-size:18px;font-weight:700;margin:0 0 14px">Detailed Test Log</h2>
  <table>
    <thead><tr><th>Step</th><th>Module</th><th>Data Checked</th><th>Booking ID</th><th>Status</th><th>Detail</th><th>Time</th></tr></thead>
    <tbody>{step_rows}</tbody>
  </table>
</div>
<footer>Mehad Autonomous QA · Data Flow Suite · Run #{RUN_NUMBER} · All data real (no mocks)</footer>
</body></html>"""

    out = site_dir / "data-flow.html"
    out.write_text(html, encoding="utf-8")
    print(f"  ✅ data-flow.html generated ({passed}/{total} passed, booking={bid})")


def main() -> None:
    SITE_DIR.mkdir(exist_ok=True)
    (SITE_DIR / "agents").mkdir(exist_ok=True)
    (SITE_DIR / "history").mkdir(exist_ok=True)
    archive = _archive_dir()

    # 1. Master report at /report.html (and archived copy at /history/run-N.html)
    master = REPORTS_DIR / "bug-report.html"
    if master.exists():
        shutil.copy(master, SITE_DIR / "report.html")
        shutil.copy(master, SITE_DIR / "history" / f"run-{RUN_NUMBER}.html")
        print(f"  ✅ master report → report.html  +  history/run-{RUN_NUMBER}.html")
        # 1a-inject: embed a Data Flow banner at the top of report.html so the
        # CEO can navigate directly to the data-flow results page.
        _inject_data_flow_banner(SITE_DIR / "report.html")
    else:
        print("  ⚠️  reports/bug-report.html not found — site will have no master report")

    # 1z. Generate data-flow.html from realtime/DF test JSON reports
    _build_data_flow_page(REPORTS_DIR, SITE_DIR)

    # 1b. Copy the embedded-videos directory so <video src="videos-embed/..."> works.
    videos_embed = REPORTS_DIR / "videos-embed"
    if videos_embed.exists() and any(videos_embed.iterdir()):
        dest_videos = SITE_DIR / "videos-embed"
        if dest_videos.exists():
            shutil.rmtree(dest_videos)
        shutil.copytree(videos_embed, dest_videos)
        # Also copy into archived per-run folder so historical reports keep their videos
        shutil.copytree(videos_embed, archive / "videos-embed")
        n_videos = sum(1 for _ in dest_videos.glob("*.webm"))
        print(f"  ✅ videos-embed/ copied ({n_videos} video(s))")

    # 1c. Persist trends.json on the site root so the next CI run can fetch
    # it via https://<owner>.github.io/<repo>/trends.json — this is what
    # makes cumulative trend tracking actually work across runs.
    trends_src = REPORTS_DIR / "trends.json"
    if trends_src.exists():
        shutil.copy(trends_src, SITE_DIR / "trends.json")
        # Also save a per-run snapshot for historical inspection
        shutil.copy(trends_src, archive / "trends.json")
        print(f"  ✅ trends.json published to site root")

    # 1d. Publish AI test-code cache so the next CI run can reuse generated
    # tests for unchanged specs (skips slow Ollama calls). cache/tests/<slug>.json
    # is fetched at the start of the next run via _restore_cache_from_gh_pages.
    cache_dir = ROOT / "cache" / "tests"
    if cache_dir.exists() and any(cache_dir.iterdir()):
        dest_cache = SITE_DIR / "cache" / "tests"
        if dest_cache.exists():
            shutil.rmtree(dest_cache)
        dest_cache.mkdir(parents=True, exist_ok=True)
        for f in cache_dir.glob("*.json"):
            shutil.copy(f, dest_cache / f.name)
        n = sum(1 for _ in dest_cache.glob("*.json"))
        print(f"  ✅ AI test cache published ({n} spec(s) cached)")

    # 2. Per-agent reports under /agents/ (and archived copy). Prefer the
    #    custom Mehad-styled `agent-<src>.html` over the default pytest-html
    #    output. Fall back to pytest-html only if no custom report exists.
    found_agents = 0
    for custom_src, public_name, _label, _emoji in AGENT_REPORTS:
        src = _has_agent_report(custom_src, public_name)
        if src is not None:
            shutil.copy(src, SITE_DIR / "agents" / public_name)
            (archive / "agents").mkdir(exist_ok=True)
            shutil.copy(src, archive / "agents" / public_name)
            found_agents += 1
    print(f"  ✅ per-agent reports: {found_agents}/{len(AGENT_REPORTS)}")

    # 3. Build index.html
    summary = _load_summary()
    # History sources, in priority order:
    #   (a) trends.json — cumulative across all runs (gh-pages backed),
    #       knows about runs even if their run-N.html was cleaned up
    #   (b) local SITE_DIR/history/run-*.html — files the build script
    #       just emitted or copied into the deploy dir
    #   (c) the current RUN_NUMBER itself (so a fresh first deployment shows up)
    # Then dedupe BY RUN NUMBER (not by Path tuple — Path strings differ
    # between absolute filesystem entries and relative href strings, which
    # was causing duplicate "Run #N" rows to appear).
    history_runs: dict[int, Path] = {}
    for n, p in _existing_history(SITE_DIR):
        history_runs[n] = Path(f"history/run-{n}.html")
    # Pull every run number trends.json knows about
    try:
        trends_path = SITE_DIR / "trends.json"
        if trends_path.exists():
            tdata = json.loads(trends_path.read_text(encoding="utf-8"))
            for entry in tdata.get("history", []) or tdata.get("runs", []):
                n = entry.get("run") or entry.get("run_number")
                if n is not None:
                    try:
                        history_runs.setdefault(int(n),
                                                  Path(f"history/run-{int(n)}.html"))
                    except (TypeError, ValueError):
                        pass
    except Exception as e:
        print(f"  ⚠️  Could not merge trends.json into history: {e}")
    # Always include the current run if its html was emitted
    if (SITE_DIR / "history" / f"run-{RUN_NUMBER}.html").exists():
        try:
            n = int(RUN_NUMBER)
            history_runs[n] = Path(f"history/run-{n}.html")
        except Exception:
            pass
    history = sorted(history_runs.items(), reverse=True)

    (SITE_DIR / "index.html").write_text(
        _build_index_html(summary, history), encoding="utf-8")
    print(f"  ✅ index.html built ({len(history)} runs in history)")

    # 3b. OTP setup page
    (SITE_DIR / "otp-setup.html").write_text(
        _build_otp_setup_html(), encoding="utf-8")
    print(f"  ✅ otp-setup.html built")

    # 4. History index page (with unified footer)
    # Build ts_map for the history page (same source as index.html)
    _trends_hist = _load_trends()
    _ts_map_hist: dict[int, str] = {
        int(r["run_number"]): r.get("timestamp", "")
        for r in _trends_hist.get("runs", [])
        if r.get("run_number") and r.get("timestamp")
    }
    rows = []
    for run_num, _ in history[:50]:
        ts = _fmt_run_ts(run_num, _ts_map_hist)
        ts_str = (f'<span style="color:#8b949e;font-size:12px;margin-left:10px">'
                  f'🕐 {ts}</span>') if ts else ""
        rows.append(f'<li><a href="run-{run_num}.html">Run #{run_num}</a>{ts_str}</li>')
    (SITE_DIR / "history" / "index.html").write_text(f"""<!DOCTYPE html>
<html><head><meta charset="UTF-8"/>
<meta name="viewport" content="width=device-width,initial-scale=1"/>
<title>Mehad QA — History</title>
<style>
* {{ box-sizing:border-box }}
body{{font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,sans-serif;
     background:#0d1117;color:#e6edf3;padding:32px;max-width:720px;margin:0 auto;
     line-height:1.5}}
h1{{color:#58a6ff;margin-top:0}}
a{{color:#58a6ff;text-decoration:none}}
a:hover{{text-decoration:underline}}
ul{{list-style:none;padding:0}}
li{{padding:10px 12px;border-bottom:1px solid #30363d;border-radius:4px;
   transition:background .12s}}
li:hover{{background:#161b22}}
.footer{{margin-top:44px;padding:24px 12px;text-align:center;
        color:#8b949e;font-size:12px;border-top:1px solid #30363d}}
.footer .contact-card{{display:inline-flex;flex-direction:column;align-items:center;
                      gap:6px;padding:18px 28px;margin:14px auto 0;
                      background:#161b22;border:1px solid #30363d;border-radius:10px}}
.footer .contact-card .name {{font-weight:700;font-size:15px;color:#e6edf3}}
.footer .contact-card .title{{font-size:12px;color:#8b949e}}
.footer .contact-card .links a{{display:inline-block;color:#58a6ff;
                               font-size:12px;padding:5px 14px;margin-top:8px;
                               border:1px solid #30363d;border-radius:6px;
                               background:#0d1117}}
.footer .contact-card .links a:hover{{background:#1c2333;border-color:#58a6ff}}
@media (max-width:480px) {{ body{{padding:16px}} h1{{font-size:22px}} }}
</style></head>
<body>
<h1>QA Report History</h1>
<p><a href="../index.html">← Back to latest</a></p>
<ul>{"".join(rows)}</ul>
<div class="footer">
  <div style="margin-bottom:6px">Built by Mejbaur Bahar Fagun</div>
  <div class="contact-card">
    <div class="name">Mejbaur Bahar Fagun</div>
    <div class="title">Senior Software Engineer QA (IV) · Markopolo.ai</div>
    <div class="links"><a href="https://www.linkedin.com/in/mejbaur/" target="_blank" rel="noopener">💼 LinkedIn</a></div>
  </div>
</div>
</body></html>""", encoding="utf-8")
    print(f"  ✅ history/index.html with {len(history)} entries")

    print(f"\nSite ready at: {SITE_DIR}")
    print(f"Files: {sum(1 for _ in SITE_DIR.rglob('*.html'))} HTML pages")


if __name__ == "__main__":
    main()
